run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - goimports
    - revive

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/sh1/terraform-provider-rtx
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Ignore long lines in test files
    - path: _test\.go
      linters:
        - lll
    # Ignore unused parameters in test files
    - path: _test\.go
      linters:
        - unparam
    # Ignore var-naming for test functions (testAccXxx_yyy is standard Terraform convention)
    - path: _test\.go
      linters:
        - revive
      text: "var-naming.*testAcc"
    # Ignore d.Set error return checks (standard Terraform provider pattern)
    - linters:
        - errcheck
      text: "Error return value of `d.Set` is not checked"
    # Ignore Close() error return checks in deferred cleanup
    - linters:
        - errcheck
      text: "Error return value of `.*\\.Close` is not checked"
    # Ignore fmt.Fprintln error checks (typically for prompt writing)
    - linters:
        - errcheck
      text: "Error return value of `fmt.Fprintln` is not checked"
