// Code generated by specgen. DO NOT EDIT.
// Source: specs/admin_config.yaml
// Command: admin_config
// Reference:

package parsers

import (
	"strings"
	"testing"
)

// TestSpecAdminConfigRTXSyntax validates that RTX commands in spec are well-formed
func TestSpecAdminConfigRTXSyntax(t *testing.T) {
	// This test validates that all RTX command strings in the spec are well-formed
	// and follow expected patterns

	testCases := []struct {
		name       string
		rtxCommand string
		parseOnly  bool
		buildOnly  bool
	}{
		{
			name:       "login_password_simple",
			rtxCommand: `login password secret123`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "login_password_complex",
			rtxCommand: `login password MyP@ssw0rd!#$`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "admin_password_simple",
			rtxCommand: `administrator password admin123`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "admin_password_complex",
			rtxCommand: `administrator password Adm!n@2024`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "login_user_plain",
			rtxCommand: `login user operator password123`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "login_user_encrypted",
			rtxCommand: `login user admin encrypted abc123def456`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "login_user_readonly",
			rtxCommand: `login user readonly pass123`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "user_attribute_administrator",
			rtxCommand: `user attribute admin administrator=on`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "user_attribute_connection",
			rtxCommand: `user attribute operator connection=telnet,ssh`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "user_attribute_gui_page",
			rtxCommand: `user attribute webuser gui-page=dashboard,lan-map`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "user_attribute_login_timer",
			rtxCommand: `user attribute admin login-timer=3600`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "user_attribute_multiple",
			rtxCommand: `user attribute admin administrator=on connection=serial,telnet,ssh gui-page=dashboard,config login-timer=7200`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "delete_login_user",
			rtxCommand: `no login user operator`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "delete_user_attribute",
			rtxCommand: `no user attribute admin`,
			parseOnly:  false,
			buildOnly:  true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Validate RTX command is not empty
			if strings.TrimSpace(tc.rtxCommand) == "" {
				t.Errorf("RTX command should not be empty")
			}

			// Validate command doesn't have trailing/leading whitespace issues
			trimmed := strings.TrimSpace(tc.rtxCommand)
			if tc.rtxCommand != trimmed && !strings.Contains(tc.rtxCommand, "\n") {
				t.Errorf("RTX command has unexpected whitespace: %q", tc.rtxCommand)
			}

			// Log the command for visibility
			if !tc.buildOnly {
				t.Logf("Parse test: %s", tc.rtxCommand)
			}
			if !tc.parseOnly {
				t.Logf("Build test: %s", tc.rtxCommand)
			}
		})
	}
}

// TestSpecAdminConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecAdminConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "login_password_simple",
			rtxCommand:  `login password secret123`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "login_password_complex",
			rtxCommand:  `login password MyP@ssw0rd!#$`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "admin_password_simple",
			rtxCommand:  `administrator password admin123`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "admin_password_complex",
			rtxCommand:  `administrator password Adm!n@2024`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "login_user_plain",
			rtxCommand:  `login user operator password123`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "login_user_encrypted",
			rtxCommand:  `login user admin encrypted abc123def456`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "login_user_readonly",
			rtxCommand:  `login user readonly pass123`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "user_attribute_administrator",
			rtxCommand:  `user attribute admin administrator=on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "user_attribute_connection",
			rtxCommand:  `user attribute operator connection=telnet,ssh`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "user_attribute_gui_page",
			rtxCommand:  `user attribute webuser gui-page=dashboard,lan-map`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "user_attribute_login_timer",
			rtxCommand:  `user attribute admin login-timer=3600`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "user_attribute_multiple",
			rtxCommand:  `user attribute admin administrator=on connection=serial,telnet,ssh gui-page=dashboard,config login-timer=7200`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_login_user",
			rtxCommand:  `no login user operator`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_user_attribute",
			rtxCommand:  `no user attribute admin`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecAdminConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecAdminConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"connection",
		"gui_page",
		"login_timer",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}

// TestSpecAdminConfigModelCompatibility tests router model compatibility
func TestSpecAdminConfigModelCompatibility(t *testing.T) {
	// All known RTX router models
	allModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
		"RTX810",
		"NVR700W",
		"NVR510",
		"NVR500",
	}

	// Models that support this command according to the spec
	supportedModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
	}

	// Build a map for quick lookup
	supportedMap := make(map[string]bool)
	for _, m := range supportedModels {
		supportedMap[m] = true
	}

	// Find unsupported models
	var unsupportedModels []string
	for _, m := range allModels {
		if !supportedMap[m] {
			unsupportedModels = append(unsupportedModels, m)
		}
	}

	t.Logf("Command: admin_config")
	t.Logf("Supported models (%d): %v", len(supportedModels), supportedModels)
	t.Logf("Unsupported models (%d): %v", len(unsupportedModels), unsupportedModels)

	// Test: Verify supported models are recognized
	for _, model := range supportedModels {
		t.Run("supported_"+model, func(t *testing.T) {
			if !IsModelSupported("admin_config", model) {
				t.Errorf("Model %s should be supported for admin_config", model)
			}
		})
	}

	// Test: Verify unsupported models are rejected
	for _, model := range unsupportedModels {
		t.Run("unsupported_"+model, func(t *testing.T) {
			if IsModelSupported("admin_config", model) {
				t.Errorf("Model %s should NOT be supported for admin_config", model)
			}
		})
	}
}
