// Code generated by specgen. DO NOT EDIT.
// Source: specs/bgp_config.yaml
// Command: bgp_config
// Reference:

package parsers

import (
	"strings"
	"testing"
)

// TestSpecBgpConfigRTXSyntax validates that RTX commands in spec are well-formed
func TestSpecBgpConfigRTXSyntax(t *testing.T) {
	// This test validates that all RTX command strings in the spec are well-formed
	// and follow expected patterns

	testCases := []struct {
		name       string
		rtxCommand string
		parseOnly  bool
		buildOnly  bool
	}{
		{
			name:       "bgp_use_on",
			rtxCommand: `bgp use on`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_use_off",
			rtxCommand: `bgp use off`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_asn_2byte",
			rtxCommand: `bgp autonomous-system 65001`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_asn_4byte",
			rtxCommand: `bgp autonomous-system 4200000001`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_router_id",
			rtxCommand: `bgp router id 192.168.1.1`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_router_id_loopback",
			rtxCommand: `bgp router id 10.0.0.1`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_neighbor",
			rtxCommand: `bgp neighbor 1 address 203.0.113.1 as 65002`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_neighbor_second",
			rtxCommand: `bgp neighbor 2 address 203.0.113.2 as 65003`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_neighbor_4byte_as",
			rtxCommand: `bgp neighbor 1 address 10.0.0.1 as 4200000001`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_neighbor_holdtime",
			rtxCommand: `bgp neighbor 1 hold-time 90`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_neighbor_keepalive",
			rtxCommand: `bgp neighbor 1 keepalive 30`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_neighbor_multihop",
			rtxCommand: `bgp neighbor 1 multihop 2`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_neighbor_password",
			rtxCommand: `bgp neighbor 1 password mysecret`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_neighbor_local_address",
			rtxCommand: `bgp neighbor 1 local-address 192.168.1.1`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_network",
			rtxCommand: `bgp import filter 1 include 192.168.0.0/16`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_network_24",
			rtxCommand: `bgp import filter 1 include 10.0.0.0/24`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_import_static",
			rtxCommand: `bgp import from static`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bgp_import_connected",
			rtxCommand: `bgp import from connected`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "delete_bgp_neighbor",
			rtxCommand: `no bgp neighbor 1`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "delete_bgp_network",
			rtxCommand: `no bgp import filter 1`,
			parseOnly:  false,
			buildOnly:  true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Validate RTX command is not empty
			if strings.TrimSpace(tc.rtxCommand) == "" {
				t.Errorf("RTX command should not be empty")
			}

			// Validate command doesn't have trailing/leading whitespace issues
			trimmed := strings.TrimSpace(tc.rtxCommand)
			if tc.rtxCommand != trimmed && !strings.Contains(tc.rtxCommand, "\n") {
				t.Errorf("RTX command has unexpected whitespace: %q", tc.rtxCommand)
			}

			// Log the command for visibility
			if !tc.buildOnly {
				t.Logf("Parse test: %s", tc.rtxCommand)
			}
			if !tc.parseOnly {
				t.Logf("Build test: %s", tc.rtxCommand)
			}
		})
	}
}

// TestSpecBgpConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecBgpConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "bgp_use_on",
			rtxCommand:  `bgp use on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_use_off",
			rtxCommand:  `bgp use off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_asn_2byte",
			rtxCommand:  `bgp autonomous-system 65001`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_asn_4byte",
			rtxCommand:  `bgp autonomous-system 4200000001`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_router_id",
			rtxCommand:  `bgp router id 192.168.1.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_router_id_loopback",
			rtxCommand:  `bgp router id 10.0.0.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_neighbor",
			rtxCommand:  `bgp neighbor 1 address 203.0.113.1 as 65002`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_neighbor_second",
			rtxCommand:  `bgp neighbor 2 address 203.0.113.2 as 65003`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_neighbor_4byte_as",
			rtxCommand:  `bgp neighbor 1 address 10.0.0.1 as 4200000001`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_neighbor_holdtime",
			rtxCommand:  `bgp neighbor 1 hold-time 90`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_neighbor_keepalive",
			rtxCommand:  `bgp neighbor 1 keepalive 30`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_neighbor_multihop",
			rtxCommand:  `bgp neighbor 1 multihop 2`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_neighbor_password",
			rtxCommand:  `bgp neighbor 1 password mysecret`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_neighbor_local_address",
			rtxCommand:  `bgp neighbor 1 local-address 192.168.1.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_network",
			rtxCommand:  `bgp import filter 1 include 192.168.0.0/16`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_network_24",
			rtxCommand:  `bgp import filter 1 include 10.0.0.0/24`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_import_static",
			rtxCommand:  `bgp import from static`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bgp_import_connected",
			rtxCommand:  `bgp import from connected`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_bgp_neighbor",
			rtxCommand:  `no bgp neighbor 1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_bgp_network",
			rtxCommand:  `no bgp import filter 1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecBgpConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecBgpConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"asn",
		"hold_time",
		"keepalive",
		"multihop",
		"neighbor_id",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}

// TestSpecBgpConfigModelCompatibility tests router model compatibility
func TestSpecBgpConfigModelCompatibility(t *testing.T) {
	// All known RTX router models
	allModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
		"RTX810",
		"NVR700W",
		"NVR510",
		"NVR500",
	}

	// Models that support this command according to the spec
	supportedModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
	}

	// Build a map for quick lookup
	supportedMap := make(map[string]bool)
	for _, m := range supportedModels {
		supportedMap[m] = true
	}

	// Find unsupported models
	var unsupportedModels []string
	for _, m := range allModels {
		if !supportedMap[m] {
			unsupportedModels = append(unsupportedModels, m)
		}
	}

	t.Logf("Command: bgp_config")
	t.Logf("Supported models (%d): %v", len(supportedModels), supportedModels)
	t.Logf("Unsupported models (%d): %v", len(unsupportedModels), unsupportedModels)

	// Test: Verify supported models are recognized
	for _, model := range supportedModels {
		t.Run("supported_"+model, func(t *testing.T) {
			if !IsModelSupported("bgp_config", model) {
				t.Errorf("Model %s should be supported for bgp_config", model)
			}
		})
	}

	// Test: Verify unsupported models are rejected
	for _, model := range unsupportedModels {
		t.Run("unsupported_"+model, func(t *testing.T) {
			if IsModelSupported("bgp_config", model) {
				t.Errorf("Model %s should NOT be supported for bgp_config", model)
			}
		})
	}
}
