// Code generated by specgen. DO NOT EDIT.
// Source: specs/dhcp_scope_lease_type.yaml
// Command: dhcp_scope_lease_type
// Reference: 12.1.6

package parsers

import (
	"encoding/json"
	"strings"
	"testing"
)

// TestSpecDhcpScopeLeaseTypeRTXSyntax validates that RTX commands in spec are well-formed
func TestSpecDhcpScopeLeaseTypeRTXSyntax(t *testing.T) {
	// This test validates that all RTX command strings in the spec are well-formed
	// and follow expected patterns

	testCases := []struct {
		name       string
		rtxCommand string
		parseOnly  bool
		buildOnly  bool
	}{
		{
			name:       "lease_type_bind_priority",
			rtxCommand: `dhcp scope lease type 1 bind-priority`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "lease_type_bind_only",
			rtxCommand: `dhcp scope lease type 1 bind-only`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "lease_type_bind_only_with_fallback",
			rtxCommand: `dhcp scope lease type 1 bind-only fallback=2`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "lease_type_large_scope_id",
			rtxCommand: `dhcp scope lease type 65535 bind-priority`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "lease_type_with_large_fallback",
			rtxCommand: `dhcp scope lease type 1 bind-only fallback=65535`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "delete_lease_type",
			rtxCommand: `no dhcp scope lease type 1`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "delete_lease_type_with_type",
			rtxCommand: `no dhcp scope lease type 1 bind-only`,
			parseOnly:  false,
			buildOnly:  true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Validate RTX command is not empty
			if strings.TrimSpace(tc.rtxCommand) == "" {
				t.Errorf("RTX command should not be empty")
			}

			// Validate command doesn't have trailing/leading whitespace issues
			trimmed := strings.TrimSpace(tc.rtxCommand)
			if tc.rtxCommand != trimmed && !strings.Contains(tc.rtxCommand, "\n") {
				t.Errorf("RTX command has unexpected whitespace: %q", tc.rtxCommand)
			}

			// Log the command for visibility
			if !tc.buildOnly {
				t.Logf("Parse test: %s", tc.rtxCommand)
			}
			if !tc.parseOnly {
				t.Logf("Build test: %s", tc.rtxCommand)
			}
		})
	}
}

// TestSpecDhcpScopeLeaseTypeSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecDhcpScopeLeaseTypeSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "lease_type_bind_priority",
			rtxCommand:  `dhcp scope lease type 1 bind-priority`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "lease_type_bind_only",
			rtxCommand:  `dhcp scope lease type 1 bind-only`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "lease_type_bind_only_with_fallback",
			rtxCommand:  `dhcp scope lease type 1 bind-only fallback=2`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "lease_type_large_scope_id",
			rtxCommand:  `dhcp scope lease type 65535 bind-priority`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "lease_type_with_large_fallback",
			rtxCommand:  `dhcp scope lease type 1 bind-only fallback=65535`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_lease_type",
			rtxCommand:  `no dhcp scope lease type 1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_lease_type_with_type",
			rtxCommand:  `no dhcp scope lease type 1 bind-only`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecDhcpScopeLeaseTypeBoundaryCoverage documents the boundary values covered by this spec
func TestSpecDhcpScopeLeaseTypeBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"fallback_scope_num",
		"scope_num",
		"type",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}

// TestSpecDhcpScopeLeaseTypeRTXTerraformMapping validates RTX command to Terraform value mappings
func TestSpecDhcpScopeLeaseTypeRTXTerraformMapping(t *testing.T) {
	// This test validates that each RTX command has a corresponding expected Terraform value
	// and vice versa. It ensures the spec file correctly documents the bidirectional mapping.

	testCases := []struct {
		name          string
		rtxCommand    string
		terraformJSON string
		parseOnly     bool
		buildOnly     bool
	}{
		{
			name:          "lease_type_bind_priority",
			rtxCommand:    `dhcp scope lease type 1 bind-priority`,
			terraformJSON: `{"lease_type":"bind-priority","scope_id":1}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "lease_type_bind_only",
			rtxCommand:    `dhcp scope lease type 1 bind-only`,
			terraformJSON: `{"lease_type":"bind-only","scope_id":1}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "lease_type_bind_only_with_fallback",
			rtxCommand:    `dhcp scope lease type 1 bind-only fallback=2`,
			terraformJSON: `{"fallback_scope":2,"lease_type":"bind-only","scope_id":1}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "lease_type_large_scope_id",
			rtxCommand:    `dhcp scope lease type 65535 bind-priority`,
			terraformJSON: `{"lease_type":"bind-priority","scope_id":65535}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "lease_type_with_large_fallback",
			rtxCommand:    `dhcp scope lease type 1 bind-only fallback=65535`,
			terraformJSON: `{"fallback_scope":65535,"lease_type":"bind-only","scope_id":1}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "delete_lease_type",
			rtxCommand:    `no dhcp scope lease type 1`,
			terraformJSON: `{"scope_id":1}`,
			parseOnly:     false,
			buildOnly:     true,
		},
		{
			name:          "delete_lease_type_with_type",
			rtxCommand:    `no dhcp scope lease type 1 bind-only`,
			terraformJSON: `{"lease_type":"bind-only","scope_id":1}`,
			parseOnly:     false,
			buildOnly:     true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Validate RTX command is not empty
			if strings.TrimSpace(tc.rtxCommand) == "" {
				t.Errorf("RTX command should not be empty")
				return
			}

			// build_only tests (like delete commands) may have empty terraform values
			// because they represent commands that don't have a direct terraform mapping
			if tc.buildOnly {
				t.Logf("Direction: Terraform -> RTX only (build)")
				t.Logf("RTX: %s", tc.rtxCommand)
				t.Logf("Terraform: %s (build_only, may be empty)", tc.terraformJSON)
				return
			}

			// Validate terraform JSON is present and valid for non-build_only tests
			if tc.terraformJSON == "null" || tc.terraformJSON == "" {
				t.Errorf("Terraform value is missing for RTX command: %s", tc.rtxCommand)
				return
			}

			var tfValue interface{}
			if err := json.Unmarshal([]byte(tc.terraformJSON), &tfValue); err != nil {
				t.Errorf("Invalid terraform JSON: %v\nJSON: %s", err, tc.terraformJSON)
				return
			}

			// Log the mapping for visibility
			t.Logf("RTX: %s", tc.rtxCommand)
			t.Logf("Terraform: %s", tc.terraformJSON)

			// Validate that terraform value contains expected fields (only for non-build_only tests)
			if tfMap, ok := tfValue.(map[string]interface{}); ok {
				if len(tfMap) == 0 {
					t.Errorf("Terraform value is empty map for RTX command: %s", tc.rtxCommand)
					return
				}
			}

			// Check mapping direction
			if tc.parseOnly {
				t.Logf("Direction: RTX -> Terraform only (parse)")
			} else {
				t.Logf("Direction: Bidirectional (parse and build)")
			}
		})
	}
}

// TestSpecDhcpScopeLeaseTypeModelCompatibility tests router model compatibility
func TestSpecDhcpScopeLeaseTypeModelCompatibility(t *testing.T) {
	// All known RTX router models
	allModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
		"RTX810",
		"NVR700W",
		"NVR510",
		"NVR500",
	}

	// Models that support this command according to the spec
	supportedModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
	}

	// Build a map for quick lookup
	supportedMap := make(map[string]bool)
	for _, m := range supportedModels {
		supportedMap[m] = true
	}

	// Find unsupported models
	var unsupportedModels []string
	for _, m := range allModels {
		if !supportedMap[m] {
			unsupportedModels = append(unsupportedModels, m)
		}
	}

	t.Logf("Command: dhcp_scope_lease_type")
	t.Logf("Supported models (%d): %v", len(supportedModels), supportedModels)
	t.Logf("Unsupported models (%d): %v", len(unsupportedModels), unsupportedModels)

	// Test: Verify supported models are recognized
	for _, model := range supportedModels {
		t.Run("supported_"+model, func(t *testing.T) {
			if !IsModelSupported("dhcp_scope_lease_type", model) {
				t.Errorf("Model %s should be supported for dhcp_scope_lease_type", model)
			}
		})
	}

	// Test: Verify unsupported models are rejected
	for _, model := range unsupportedModels {
		t.Run("unsupported_"+model, func(t *testing.T) {
			if IsModelSupported("dhcp_scope_lease_type", model) {
				t.Errorf("Model %s should NOT be supported for dhcp_scope_lease_type", model)
			}
		})
	}
}
