// Code generated by specgen. DO NOT EDIT.
// Source: specs/dhcp/service.yaml
// This file tests RTX <-> Terraform round-trip conversions using actual parsers

package parsers

import (
	"testing"
)

// TestDHCPServiceRoundTrip_Parse tests RTX command -> Terraform value conversion
func TestDHCPServiceRoundTrip_Parse(t *testing.T) {
	parser := NewDHCPServiceParser()

	testCases := []struct {
		name      string
		rtx       string
		checkFunc func(t *testing.T, config *DHCPServiceConfig)
	}{
		{
			name: "dhcp_service_server",
			rtx:  "dhcp service server",
			checkFunc: func(t *testing.T, config *DHCPServiceConfig) {
				if config.ServiceType != "server" {
					t.Errorf("ServiceType = %v, want server", config.ServiceType)
				}
			},
		},
		{
			name: "dhcp_service_relay",
			rtx:  "dhcp service relay",
			checkFunc: func(t *testing.T, config *DHCPServiceConfig) {
				if config.ServiceType != "relay" {
					t.Errorf("ServiceType = %v, want relay", config.ServiceType)
				}
			},
		},
		{
			name: "no_dhcp_service",
			rtx:  "",
			checkFunc: func(t *testing.T, config *DHCPServiceConfig) {
				if config.ServiceType != "" {
					t.Errorf("ServiceType = %v, want empty", config.ServiceType)
				}
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			config, err := parser.ParseServiceConfig(tc.rtx)
			if err != nil {
				t.Fatalf("ParseServiceConfig(%q) error = %v", tc.rtx, err)
			}
			tc.checkFunc(t, config)
		})
	}
}

// TestDHCPServiceRoundTrip_Build tests Terraform value -> RTX command conversion
func TestDHCPServiceRoundTrip_Build(t *testing.T) {
	testCases := []struct {
		name        string
		buildFunc   func() string
		expectedRTX string
	}{
		{
			name: "dhcp_service_server",
			buildFunc: func() string {
				return BuildDHCPServiceCommand("server")
			},
			expectedRTX: "dhcp service server",
		},
		{
			name: "dhcp_service_relay",
			buildFunc: func() string {
				return BuildDHCPServiceCommand("relay")
			},
			expectedRTX: "dhcp service relay",
		},
		{
			name: "dhcp_service_empty",
			buildFunc: func() string {
				return BuildDHCPServiceCommand("")
			},
			expectedRTX: "",
		},
		{
			name: "delete_dhcp_service",
			buildFunc: func() string {
				return BuildDeleteDHCPServiceCommand()
			},
			expectedRTX: "no dhcp service",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			got := tc.buildFunc()
			if got != tc.expectedRTX {
				t.Errorf("Build() = %q, want %q", got, tc.expectedRTX)
			}
		})
	}
}

// TestDHCPServiceRoundTrip_ParseBuildParse tests full round-trip
func TestDHCPServiceRoundTrip_ParseBuildParse(t *testing.T) {
	parser := NewDHCPServiceParser()

	t.Run("dhcp_service_server_round_trip", func(t *testing.T) {
		rtx := "dhcp service server"

		// Parse
		config, err := parser.ParseServiceConfig(rtx)
		if err != nil {
			t.Fatalf("ParseServiceConfig error: %v", err)
		}

		// Build
		rebuilt := BuildDHCPServiceCommand(config.ServiceType)

		// Verify
		if rebuilt != rtx {
			t.Errorf("Round-trip failed:\n  Original: %q\n  Rebuilt:  %q", rtx, rebuilt)
		}
	})

	t.Run("dhcp_service_relay_round_trip", func(t *testing.T) {
		rtx := "dhcp service relay"

		// Parse
		config, err := parser.ParseServiceConfig(rtx)
		if err != nil {
			t.Fatalf("ParseServiceConfig error: %v", err)
		}

		// Build
		rebuilt := BuildDHCPServiceCommand(config.ServiceType)

		// Verify
		if rebuilt != rtx {
			t.Errorf("Round-trip failed:\n  Original: %q\n  Rebuilt:  %q", rtx, rebuilt)
		}
	})
}

// TestDHCPServiceRoundTrip_Validation tests DHCP service validation functions
func TestDHCPServiceRoundTrip_Validation(t *testing.T) {
	testCases := []struct {
		name        string
		serviceType string
		wantError   bool
	}{
		{
			name:        "valid_server",
			serviceType: "server",
			wantError:   false,
		},
		{
			name:        "valid_relay",
			serviceType: "relay",
			wantError:   false,
		},
		{
			name:        "valid_empty",
			serviceType: "",
			wantError:   false,
		},
		{
			name:        "invalid_type",
			serviceType: "invalid",
			wantError:   true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			err := ValidateDHCPServiceType(tc.serviceType)
			if (err != nil) != tc.wantError {
				t.Errorf("ValidateDHCPServiceType(%q) error = %v, wantError %v", tc.serviceType, err, tc.wantError)
			}
		})
	}
}
