// Code generated by specgen. DO NOT EDIT.
// Source: specs/dhcp_scope_bind.yaml
// Command: dhcp_scope_bind
// Reference: 12.1.5

package parsers

import (
	"strings"
	"testing"
)

// TestSpecDhcpScopeBindRTXSyntax validates that RTX commands in spec are well-formed
func TestSpecDhcpScopeBindRTXSyntax(t *testing.T) {
	// This test validates that all RTX command strings in the spec are well-formed
	// and follow expected patterns

	testCases := []struct {
		name       string
		rtxCommand string
		parseOnly  bool
		buildOnly  bool
	}{
		{
			name:       "bind_mac_basic",
			rtxCommand: `dhcp scope bind 1 192.168.1.100 00:11:22:33:44:55`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_mac_lowercase",
			rtxCommand: `dhcp scope bind 1 192.168.1.101 00:aa:bb:cc:dd:ee`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_mac_mixedcase",
			rtxCommand: `dhcp scope bind 1 192.168.1.102 00:Aa:Bb:Cc:Dd:Ee`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_ethernet_type",
			rtxCommand: `dhcp scope bind 1 192.168.1.110 ethernet 00:a0:de:01:23:45`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_ethernet_type_uppercase",
			rtxCommand: `dhcp scope bind 1 192.168.1.111 ethernet B6:1A:27:EA:28:29`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_text_type",
			rtxCommand: `dhcp scope bind 1 192.168.1.120 text client01`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_hex_sequence",
			rtxCommand: `dhcp scope bind 1 192.168.1.130 01 00 a0 de 01 23 45`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_client_identifier_01",
			rtxCommand: `dhcp scope bind 1 192.168.1.102 client-id 01:00:11:22:33:44:55`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "bind_client_identifier_ff",
			rtxCommand: `dhcp scope bind 2 10.0.0.51 client-id ff:00:01:02:03:04:05`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "bind_wildcard_ip",
			rtxCommand: `dhcp scope bind 1 * 00:a0:de:01:23:45`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_oui_range",
			rtxCommand: `dhcp scope bind 1 192.168.1.20-192.168.1.30 00:a0:de:*`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_ipcp",
			rtxCommand: `dhcp scope bind 1 192.168.1.100 ipcp`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_scope_2",
			rtxCommand: `dhcp scope bind 2 10.0.0.50 11:22:33:44:55:66`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "bind_large_scope_id",
			rtxCommand: `dhcp scope bind 65535 172.16.0.100 aa:bb:cc:dd:ee:ff`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "unbind_basic",
			rtxCommand: `no dhcp scope bind 1 192.168.1.100`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "unbind_scope_2",
			rtxCommand: `no dhcp scope bind 2 10.0.0.50`,
			parseOnly:  false,
			buildOnly:  true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Validate RTX command is not empty
			if strings.TrimSpace(tc.rtxCommand) == "" {
				t.Errorf("RTX command should not be empty")
			}

			// Validate command doesn't have trailing/leading whitespace issues
			trimmed := strings.TrimSpace(tc.rtxCommand)
			if tc.rtxCommand != trimmed && !strings.Contains(tc.rtxCommand, "\n") {
				t.Errorf("RTX command has unexpected whitespace: %q", tc.rtxCommand)
			}

			// Log the command for visibility
			if !tc.buildOnly {
				t.Logf("Parse test: %s", tc.rtxCommand)
			}
			if !tc.parseOnly {
				t.Logf("Build test: %s", tc.rtxCommand)
			}
		})
	}
}

// TestSpecDhcpScopeBindSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecDhcpScopeBindSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "bind_mac_basic",
			rtxCommand:  `dhcp scope bind 1 192.168.1.100 00:11:22:33:44:55`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_mac_lowercase",
			rtxCommand:  `dhcp scope bind 1 192.168.1.101 00:aa:bb:cc:dd:ee`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_mac_mixedcase",
			rtxCommand:  `dhcp scope bind 1 192.168.1.102 00:Aa:Bb:Cc:Dd:Ee`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_ethernet_type",
			rtxCommand:  `dhcp scope bind 1 192.168.1.110 ethernet 00:a0:de:01:23:45`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_ethernet_type_uppercase",
			rtxCommand:  `dhcp scope bind 1 192.168.1.111 ethernet B6:1A:27:EA:28:29`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_text_type",
			rtxCommand:  `dhcp scope bind 1 192.168.1.120 text client01`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_hex_sequence",
			rtxCommand:  `dhcp scope bind 1 192.168.1.130 01 00 a0 de 01 23 45`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_client_identifier_01",
			rtxCommand:  `dhcp scope bind 1 192.168.1.102 client-id 01:00:11:22:33:44:55`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "bind_client_identifier_ff",
			rtxCommand:  `dhcp scope bind 2 10.0.0.51 client-id ff:00:01:02:03:04:05`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "bind_wildcard_ip",
			rtxCommand:  `dhcp scope bind 1 * 00:a0:de:01:23:45`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_oui_range",
			rtxCommand:  `dhcp scope bind 1 192.168.1.20-192.168.1.30 00:a0:de:*`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_ipcp",
			rtxCommand:  `dhcp scope bind 1 192.168.1.100 ipcp`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_scope_2",
			rtxCommand:  `dhcp scope bind 2 10.0.0.50 11:22:33:44:55:66`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "bind_large_scope_id",
			rtxCommand:  `dhcp scope bind 65535 172.16.0.100 aa:bb:cc:dd:ee:ff`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "unbind_basic",
			rtxCommand:  `no dhcp scope bind 1 192.168.1.100`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "unbind_scope_2",
			rtxCommand:  `no dhcp scope bind 2 10.0.0.50`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecDhcpScopeBindBoundaryCoverage documents the boundary values covered by this spec
func TestSpecDhcpScopeBindBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"client_identifier",
		"mac_address_format",
		"scope_num",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}

// TestSpecDhcpScopeBindModelCompatibility tests router model compatibility
func TestSpecDhcpScopeBindModelCompatibility(t *testing.T) {
	// All known RTX router models
	allModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
		"RTX810",
		"NVR700W",
		"NVR510",
		"NVR500",
	}

	// Models that support this command according to the spec
	supportedModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
	}

	// Build a map for quick lookup
	supportedMap := make(map[string]bool)
	for _, m := range supportedModels {
		supportedMap[m] = true
	}

	// Find unsupported models
	var unsupportedModels []string
	for _, m := range allModels {
		if !supportedMap[m] {
			unsupportedModels = append(unsupportedModels, m)
		}
	}

	t.Logf("Command: dhcp_scope_bind")
	t.Logf("Supported models (%d): %v", len(supportedModels), supportedModels)
	t.Logf("Unsupported models (%d): %v", len(unsupportedModels), unsupportedModels)

	// Test: Verify supported models are recognized
	for _, model := range supportedModels {
		t.Run("supported_"+model, func(t *testing.T) {
			if !IsModelSupported("dhcp_scope_bind", model) {
				t.Errorf("Model %s should be supported for dhcp_scope_bind", model)
			}
		})
	}

	// Test: Verify unsupported models are rejected
	for _, model := range unsupportedModels {
		t.Run("unsupported_"+model, func(t *testing.T) {
			if IsModelSupported("dhcp_scope_bind", model) {
				t.Errorf("Model %s should NOT be supported for dhcp_scope_bind", model)
			}
		})
	}
}
