// Code generated by specgen. DO NOT EDIT.
// Source: specs/dhcp/bindings.yaml
// This file tests RTX <-> Terraform round-trip conversions using actual parsers

package parsers

import (
	"testing"
)

// TestDHCPBindingsRoundTrip_Parse tests RTX command -> Terraform value conversion
func TestDHCPBindingsRoundTrip_Parse(t *testing.T) {
	parser := NewDHCPBindingsParser()

	testCases := []struct {
		name      string
		rtx       string
		scopeID   int
		checkFunc func(t *testing.T, bindings []DHCPBinding)
	}{
		{
			name:    "simple_mac_binding",
			rtx:     "dhcp scope bind 1 192.168.1.10 00:11:22:33:44:55",
			scopeID: 1,
			checkFunc: func(t *testing.T, bindings []DHCPBinding) {
				if len(bindings) != 1 {
					t.Errorf("Bindings count = %v, want 1", len(bindings))
					return
				}
				b := bindings[0]
				if b.ScopeID != 1 {
					t.Errorf("ScopeID = %v, want 1", b.ScopeID)
				}
				if b.IPAddress != "192.168.1.10" {
					t.Errorf("IPAddress = %v, want 192.168.1.10", b.IPAddress)
				}
				if b.MACAddress != "00:11:22:33:44:55" {
					t.Errorf("MACAddress = %v, want 00:11:22:33:44:55", b.MACAddress)
				}
			},
		},
		{
			name:    "ethernet_mac_binding",
			rtx:     "dhcp scope bind 1 192.168.1.20 ethernet 00:11:22:33:44:55",
			scopeID: 1,
			checkFunc: func(t *testing.T, bindings []DHCPBinding) {
				if len(bindings) != 1 {
					t.Errorf("Bindings count = %v, want 1", len(bindings))
					return
				}
				if !bindings[0].UseClientIdentifier {
					t.Errorf("UseClientIdentifier = %v, want true", bindings[0].UseClientIdentifier)
				}
			},
		},
		{
			name:    "ipcp_binding",
			rtx:     "dhcp scope bind 1 192.168.1.30 ipcp",
			scopeID: 1,
			checkFunc: func(t *testing.T, bindings []DHCPBinding) {
				if len(bindings) != 1 {
					t.Errorf("Bindings count = %v, want 1", len(bindings))
					return
				}
				if !bindings[0].IPCP {
					t.Errorf("IPCP = %v, want true", bindings[0].IPCP)
				}
			},
		},
		{
			name:    "oui_binding",
			rtx:     "dhcp scope bind 1 192.168.1.100-192.168.1.200 00:a0:de:*",
			scopeID: 1,
			checkFunc: func(t *testing.T, bindings []DHCPBinding) {
				if len(bindings) != 1 {
					t.Errorf("Bindings count = %v, want 1", len(bindings))
					return
				}
				b := bindings[0]
				if b.IPRangeStart != "192.168.1.100" {
					t.Errorf("IPRangeStart = %v, want 192.168.1.100", b.IPRangeStart)
				}
				if b.IPRangeEnd != "192.168.1.200" {
					t.Errorf("IPRangeEnd = %v, want 192.168.1.200", b.IPRangeEnd)
				}
				if b.OUI != "00:a0:de" {
					t.Errorf("OUI = %v, want 00:a0:de", b.OUI)
				}
			},
		},
		{
			name:    "text_identifier_binding",
			rtx:     "dhcp scope bind 1 192.168.1.40 text mydevice",
			scopeID: 1,
			checkFunc: func(t *testing.T, bindings []DHCPBinding) {
				if len(bindings) != 1 {
					t.Errorf("Bindings count = %v, want 1", len(bindings))
					return
				}
				if bindings[0].TextIdentifier != "mydevice" {
					t.Errorf("TextIdentifier = %v, want mydevice", bindings[0].TextIdentifier)
				}
			},
		},
		{
			name: "multiple_bindings",
			rtx: `dhcp scope bind 1 192.168.1.10 00:11:22:33:44:55
dhcp scope bind 1 192.168.1.20 ethernet 00:11:22:33:44:66
dhcp scope bind 1 192.168.1.30 ipcp`,
			scopeID: 1,
			checkFunc: func(t *testing.T, bindings []DHCPBinding) {
				if len(bindings) != 3 {
					t.Errorf("Bindings count = %v, want 3", len(bindings))
				}
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			bindings, err := parser.ParseBindings(tc.rtx, tc.scopeID)
			if err != nil {
				t.Fatalf("ParseBindings(%q, %d) error = %v", tc.rtx, tc.scopeID, err)
			}
			tc.checkFunc(t, bindings)
		})
	}
}

// TestDHCPBindingsRoundTrip_Build tests Terraform value -> RTX command conversion
func TestDHCPBindingsRoundTrip_Build(t *testing.T) {
	testCases := []struct {
		name        string
		buildFunc   func() string
		expectedRTX string
	}{
		{
			name: "simple_mac_binding",
			buildFunc: func() string {
				return BuildDHCPBindCommand(DHCPBinding{
					ScopeID:    1,
					IPAddress:  "192.168.1.10",
					MACAddress: "00:11:22:33:44:55",
				})
			},
			expectedRTX: "dhcp scope bind 1 192.168.1.10 00:11:22:33:44:55",
		},
		{
			name: "ethernet_mac_binding",
			buildFunc: func() string {
				return BuildDHCPBindCommand(DHCPBinding{
					ScopeID:             1,
					IPAddress:           "192.168.1.20",
					MACAddress:          "00:11:22:33:44:55",
					UseClientIdentifier: true,
				})
			},
			expectedRTX: "dhcp scope bind 1 192.168.1.20 ethernet 00:11:22:33:44:55",
		},
		{
			name: "ipcp_binding",
			buildFunc: func() string {
				return BuildDHCPBindCommand(DHCPBinding{
					ScopeID:   1,
					IPAddress: "192.168.1.30",
					IPCP:      true,
				})
			},
			expectedRTX: "dhcp scope bind 1 192.168.1.30 ipcp",
		},
		{
			name: "oui_binding",
			buildFunc: func() string {
				return BuildDHCPBindCommand(DHCPBinding{
					ScopeID:      1,
					IPRangeStart: "192.168.1.100",
					IPRangeEnd:   "192.168.1.200",
					OUI:          "00:a0:de",
				})
			},
			expectedRTX: "dhcp scope bind 1 192.168.1.100-192.168.1.200 00:a0:de:*",
		},
		{
			name: "text_identifier_binding",
			buildFunc: func() string {
				return BuildDHCPBindCommand(DHCPBinding{
					ScopeID:        1,
					IPAddress:      "192.168.1.40",
					TextIdentifier: "mydevice",
				})
			},
			expectedRTX: "dhcp scope bind 1 192.168.1.40 text mydevice",
		},
		{
			name: "delete_binding",
			buildFunc: func() string {
				return BuildDHCPUnbindCommand(1, "192.168.1.10")
			},
			expectedRTX: "no dhcp scope bind 1 192.168.1.10",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			got := tc.buildFunc()
			if got != tc.expectedRTX {
				t.Errorf("Build() = %q, want %q", got, tc.expectedRTX)
			}
		})
	}
}

// TestDHCPBindingsRoundTrip_ParseBuildParse tests full round-trip
func TestDHCPBindingsRoundTrip_ParseBuildParse(t *testing.T) {
	parser := NewDHCPBindingsParser()

	t.Run("simple_mac_binding_round_trip", func(t *testing.T) {
		rtx := "dhcp scope bind 1 192.168.1.10 00:11:22:33:44:55"

		// Parse
		bindings, err := parser.ParseBindings(rtx, 1)
		if err != nil {
			t.Fatalf("ParseBindings error: %v", err)
		}

		if len(bindings) != 1 {
			t.Fatalf("Expected 1 binding, got %d", len(bindings))
		}

		// Build
		rebuilt := BuildDHCPBindCommand(bindings[0])

		// Verify
		if rebuilt != rtx {
			t.Errorf("Round-trip failed:\n  Original: %q\n  Rebuilt:  %q", rtx, rebuilt)
		}
	})
}

// TestDHCPBindingsRoundTrip_MACNormalization tests MAC address normalization
func TestDHCPBindingsRoundTrip_MACNormalization(t *testing.T) {
	testCases := []struct {
		input    string
		expected string
		wantErr  bool
	}{
		{"00:11:22:33:44:55", "00:11:22:33:44:55", false},
		{"00-11-22-33-44-55", "00:11:22:33:44:55", false},
		{"001122334455", "00:11:22:33:44:55", false},
		{"AA:BB:CC:DD:EE:FF", "aa:bb:cc:dd:ee:ff", false},
		{"invalid", "", true},
		{"00:11:22", "", true}, // Too short
	}

	for _, tc := range testCases {
		t.Run(tc.input, func(t *testing.T) {
			got, err := NormalizeMACAddress(tc.input)
			if (err != nil) != tc.wantErr {
				t.Errorf("NormalizeMACAddress(%q) error = %v, wantErr %v", tc.input, err, tc.wantErr)
				return
			}
			if got != tc.expected {
				t.Errorf("NormalizeMACAddress(%q) = %q, want %q", tc.input, got, tc.expected)
			}
		})
	}
}

// TestDHCPBindingsRoundTrip_BuildWithValidation tests DHCP binding command building with validation
func TestDHCPBindingsRoundTrip_BuildWithValidation(t *testing.T) {
	testCases := []struct {
		name    string
		binding DHCPBinding
		wantErr bool
	}{
		{
			name: "valid_mac_binding",
			binding: DHCPBinding{
				ScopeID:    1,
				IPAddress:  "192.168.1.10",
				MACAddress: "00:11:22:33:44:55",
			},
			wantErr: false,
		},
		{
			name: "invalid_scope_id",
			binding: DHCPBinding{
				ScopeID:    0,
				IPAddress:  "192.168.1.10",
				MACAddress: "00:11:22:33:44:55",
			},
			wantErr: true,
		},
		{
			name: "missing_ip_address",
			binding: DHCPBinding{
				ScopeID:    1,
				MACAddress: "00:11:22:33:44:55",
			},
			wantErr: true,
		},
		{
			name: "missing_client_id",
			binding: DHCPBinding{
				ScopeID:   1,
				IPAddress: "192.168.1.10",
			},
			wantErr: true,
		},
		{
			name: "both_mac_and_client_id",
			binding: DHCPBinding{
				ScopeID:          1,
				IPAddress:        "192.168.1.10",
				MACAddress:       "00:11:22:33:44:55",
				ClientIdentifier: "01:00:11:22:33:44:55",
			},
			wantErr: true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := BuildDHCPBindCommandWithValidation(tc.binding)
			if (err != nil) != tc.wantErr {
				t.Errorf("BuildDHCPBindCommandWithValidation() error = %v, wantErr %v", err, tc.wantErr)
			}
		})
	}
}
