// Code generated by specgen. DO NOT EDIT.
// Source: specs/dhcp/lease_type.yaml
// This file tests RTX <-> Terraform round-trip conversions using actual parsers

package parsers

import (
	"testing"
)

// TestDHCPLeaseTypeRoundTrip_Parse tests RTX command -> Terraform value conversion
func TestDHCPLeaseTypeRoundTrip_Parse(t *testing.T) {
	parser := NewDHCPLeaseTypeParser()

	testCases := []struct {
		name      string
		rtx       string
		checkFunc func(t *testing.T, configs []DHCPLeaseTypeConfig)
	}{
		{
			name: "bind_only",
			rtx:  "dhcp scope lease type 1 bind-only",
			checkFunc: func(t *testing.T, configs []DHCPLeaseTypeConfig) {
				if len(configs) != 1 {
					t.Errorf("Configs count = %v, want 1", len(configs))
					return
				}
				if configs[0].ScopeID != 1 {
					t.Errorf("ScopeID = %v, want 1", configs[0].ScopeID)
				}
				if configs[0].LeaseType != "bind-only" {
					t.Errorf("LeaseType = %v, want bind-only", configs[0].LeaseType)
				}
			},
		},
		{
			name: "bind_priority",
			rtx:  "dhcp scope lease type 2 bind-priority",
			checkFunc: func(t *testing.T, configs []DHCPLeaseTypeConfig) {
				if len(configs) != 1 {
					t.Errorf("Configs count = %v, want 1", len(configs))
					return
				}
				if configs[0].ScopeID != 2 {
					t.Errorf("ScopeID = %v, want 2", configs[0].ScopeID)
				}
				if configs[0].LeaseType != "bind-priority" {
					t.Errorf("LeaseType = %v, want bind-priority", configs[0].LeaseType)
				}
			},
		},
		{
			name: "lease_only",
			rtx:  "dhcp scope lease type 3 lease-only",
			checkFunc: func(t *testing.T, configs []DHCPLeaseTypeConfig) {
				if len(configs) != 1 {
					t.Errorf("Configs count = %v, want 1", len(configs))
					return
				}
				if configs[0].ScopeID != 3 {
					t.Errorf("ScopeID = %v, want 3", configs[0].ScopeID)
				}
				if configs[0].LeaseType != "lease-only" {
					t.Errorf("LeaseType = %v, want lease-only", configs[0].LeaseType)
				}
			},
		},
		{
			name: "multiple_scopes",
			rtx: `dhcp scope lease type 1 bind-only
dhcp scope lease type 2 bind-priority
dhcp scope lease type 3 lease-only`,
			checkFunc: func(t *testing.T, configs []DHCPLeaseTypeConfig) {
				if len(configs) != 3 {
					t.Errorf("Configs count = %v, want 3", len(configs))
				}
			},
		},
		{
			name: "empty_config",
			rtx:  "",
			checkFunc: func(t *testing.T, configs []DHCPLeaseTypeConfig) {
				if len(configs) != 0 {
					t.Errorf("Configs count = %v, want 0", len(configs))
				}
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			configs, err := parser.ParseLeaseTypeConfig(tc.rtx)
			if err != nil {
				t.Fatalf("ParseLeaseTypeConfig(%q) error = %v", tc.rtx, err)
			}
			tc.checkFunc(t, configs)
		})
	}
}

// TestDHCPLeaseTypeRoundTrip_Build tests Terraform value -> RTX command conversion
func TestDHCPLeaseTypeRoundTrip_Build(t *testing.T) {
	testCases := []struct {
		name        string
		buildFunc   func() string
		expectedRTX string
	}{
		{
			name: "bind_only",
			buildFunc: func() string {
				return BuildDHCPLeaseTypeCommand(1, "bind-only")
			},
			expectedRTX: "dhcp scope lease type 1 bind-only",
		},
		{
			name: "bind_priority",
			buildFunc: func() string {
				return BuildDHCPLeaseTypeCommand(2, "bind-priority")
			},
			expectedRTX: "dhcp scope lease type 2 bind-priority",
		},
		{
			name: "lease_only",
			buildFunc: func() string {
				return BuildDHCPLeaseTypeCommand(3, "lease-only")
			},
			expectedRTX: "dhcp scope lease type 3 lease-only",
		},
		{
			name: "delete_lease_type",
			buildFunc: func() string {
				return BuildDeleteDHCPLeaseTypeCommand(1)
			},
			expectedRTX: "no dhcp scope lease type 1",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			got := tc.buildFunc()
			if got != tc.expectedRTX {
				t.Errorf("Build() = %q, want %q", got, tc.expectedRTX)
			}
		})
	}
}

// TestDHCPLeaseTypeRoundTrip_ParseBuildParse tests full round-trip
func TestDHCPLeaseTypeRoundTrip_ParseBuildParse(t *testing.T) {
	parser := NewDHCPLeaseTypeParser()

	t.Run("bind_only_round_trip", func(t *testing.T) {
		rtx := "dhcp scope lease type 1 bind-only"

		// Parse
		configs, err := parser.ParseLeaseTypeConfig(rtx)
		if err != nil {
			t.Fatalf("ParseLeaseTypeConfig error: %v", err)
		}

		if len(configs) != 1 {
			t.Fatalf("Expected 1 config, got %d", len(configs))
		}

		// Build
		rebuilt := BuildDHCPLeaseTypeCommand(configs[0].ScopeID, configs[0].LeaseType)

		// Verify
		if rebuilt != rtx {
			t.Errorf("Round-trip failed:\n  Original: %q\n  Rebuilt:  %q", rtx, rebuilt)
		}
	})

	t.Run("bind_priority_round_trip", func(t *testing.T) {
		rtx := "dhcp scope lease type 2 bind-priority"

		// Parse
		configs, err := parser.ParseLeaseTypeConfig(rtx)
		if err != nil {
			t.Fatalf("ParseLeaseTypeConfig error: %v", err)
		}

		if len(configs) != 1 {
			t.Fatalf("Expected 1 config, got %d", len(configs))
		}

		// Build
		rebuilt := BuildDHCPLeaseTypeCommand(configs[0].ScopeID, configs[0].LeaseType)

		// Verify
		if rebuilt != rtx {
			t.Errorf("Round-trip failed:\n  Original: %q\n  Rebuilt:  %q", rtx, rebuilt)
		}
	})

	t.Run("lease_only_round_trip", func(t *testing.T) {
		rtx := "dhcp scope lease type 3 lease-only"

		// Parse
		configs, err := parser.ParseLeaseTypeConfig(rtx)
		if err != nil {
			t.Fatalf("ParseLeaseTypeConfig error: %v", err)
		}

		if len(configs) != 1 {
			t.Fatalf("Expected 1 config, got %d", len(configs))
		}

		// Build
		rebuilt := BuildDHCPLeaseTypeCommand(configs[0].ScopeID, configs[0].LeaseType)

		// Verify
		if rebuilt != rtx {
			t.Errorf("Round-trip failed:\n  Original: %q\n  Rebuilt:  %q", rtx, rebuilt)
		}
	})
}

// TestDHCPLeaseTypeRoundTrip_Validation tests DHCP lease type validation functions
func TestDHCPLeaseTypeRoundTrip_Validation(t *testing.T) {
	testCases := []struct {
		name      string
		leaseType string
		wantError bool
	}{
		{
			name:      "valid_bind_only",
			leaseType: "bind-only",
			wantError: false,
		},
		{
			name:      "valid_bind_priority",
			leaseType: "bind-priority",
			wantError: false,
		},
		{
			name:      "valid_lease_only",
			leaseType: "lease-only",
			wantError: false,
		},
		{
			name:      "invalid_type",
			leaseType: "invalid",
			wantError: true,
		},
		{
			name:      "empty_type",
			leaseType: "",
			wantError: true,
		},
		{
			name:      "typo_bind",
			leaseType: "bind",
			wantError: true,
		},
		{
			name:      "typo_lease",
			leaseType: "lease",
			wantError: true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			err := ValidateDHCPLeaseType(tc.leaseType)
			if (err != nil) != tc.wantError {
				t.Errorf("ValidateDHCPLeaseType(%q) error = %v, wantError %v", tc.leaseType, err, tc.wantError)
			}
		})
	}
}
