// Code generated by specgen. DO NOT EDIT.
// Source: specs/dhcp/relay.yaml
// This file tests RTX <-> Terraform round-trip conversions using actual parsers

package parsers

import (
	"testing"
)

// TestDHCPRelayRoundTrip_ParseServer tests RTX command -> Terraform value conversion for relay server
func TestDHCPRelayRoundTrip_ParseServer(t *testing.T) {
	parser := NewDHCPRelayParser()

	testCases := []struct {
		name      string
		rtx       string
		checkFunc func(t *testing.T, config *DHCPRelayServerConfig)
	}{
		{
			name: "single_server",
			rtx:  "dhcp relay server 192.168.1.1",
			checkFunc: func(t *testing.T, config *DHCPRelayServerConfig) {
				if len(config.Servers) != 1 {
					t.Errorf("Servers count = %v, want 1", len(config.Servers))
					return
				}
				if config.Servers[0] != "192.168.1.1" {
					t.Errorf("Servers[0] = %v, want 192.168.1.1", config.Servers[0])
				}
			},
		},
		{
			name: "two_servers",
			rtx:  "dhcp relay server 192.168.1.1 192.168.1.2",
			checkFunc: func(t *testing.T, config *DHCPRelayServerConfig) {
				if len(config.Servers) != 2 {
					t.Errorf("Servers count = %v, want 2", len(config.Servers))
					return
				}
				if config.Servers[0] != "192.168.1.1" {
					t.Errorf("Servers[0] = %v, want 192.168.1.1", config.Servers[0])
				}
				if config.Servers[1] != "192.168.1.2" {
					t.Errorf("Servers[1] = %v, want 192.168.1.2", config.Servers[1])
				}
			},
		},
		{
			name: "four_servers_max",
			rtx:  "dhcp relay server 10.0.0.1 10.0.0.2 10.0.0.3 10.0.0.4",
			checkFunc: func(t *testing.T, config *DHCPRelayServerConfig) {
				if len(config.Servers) != 4 {
					t.Errorf("Servers count = %v, want 4", len(config.Servers))
				}
			},
		},
		{
			name: "empty_config",
			rtx:  "",
			checkFunc: func(t *testing.T, config *DHCPRelayServerConfig) {
				if len(config.Servers) != 0 {
					t.Errorf("Servers count = %v, want 0", len(config.Servers))
				}
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			config, err := parser.ParseRelayServerConfig(tc.rtx)
			if err != nil {
				t.Fatalf("ParseRelayServerConfig(%q) error = %v", tc.rtx, err)
			}
			tc.checkFunc(t, config)
		})
	}
}

// TestDHCPRelayRoundTrip_ParseSelect tests RTX command -> Terraform value conversion for relay select
func TestDHCPRelayRoundTrip_ParseSelect(t *testing.T) {
	parser := NewDHCPRelayParser()

	testCases := []struct {
		name      string
		rtx       string
		checkFunc func(t *testing.T, configs []DHCPRelaySelectConfig)
	}{
		{
			name: "single_select",
			rtx:  "dhcp relay select 1 192.168.1.1",
			checkFunc: func(t *testing.T, configs []DHCPRelaySelectConfig) {
				if len(configs) != 1 {
					t.Errorf("Configs count = %v, want 1", len(configs))
					return
				}
				if configs[0].ScopeID != 1 {
					t.Errorf("ScopeID = %v, want 1", configs[0].ScopeID)
				}
				if configs[0].Server != "192.168.1.1" {
					t.Errorf("Server = %v, want 192.168.1.1", configs[0].Server)
				}
			},
		},
		{
			name: "multiple_selects",
			rtx: `dhcp relay select 1 192.168.1.1
dhcp relay select 2 192.168.1.2`,
			checkFunc: func(t *testing.T, configs []DHCPRelaySelectConfig) {
				if len(configs) != 2 {
					t.Errorf("Configs count = %v, want 2", len(configs))
				}
			},
		},
		{
			name: "empty_config",
			rtx:  "",
			checkFunc: func(t *testing.T, configs []DHCPRelaySelectConfig) {
				if len(configs) != 0 {
					t.Errorf("Configs count = %v, want 0", len(configs))
				}
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			configs, err := parser.ParseRelaySelectConfig(tc.rtx)
			if err != nil {
				t.Fatalf("ParseRelaySelectConfig(%q) error = %v", tc.rtx, err)
			}
			tc.checkFunc(t, configs)
		})
	}
}

// TestDHCPRelayRoundTrip_Build tests Terraform value -> RTX command conversion
func TestDHCPRelayRoundTrip_Build(t *testing.T) {
	testCases := []struct {
		name        string
		buildFunc   func() string
		expectedRTX string
	}{
		{
			name: "relay_server_single",
			buildFunc: func() string {
				return BuildDHCPRelayServerCommand([]string{"192.168.1.1"})
			},
			expectedRTX: "dhcp relay server 192.168.1.1",
		},
		{
			name: "relay_server_multiple",
			buildFunc: func() string {
				return BuildDHCPRelayServerCommand([]string{"192.168.1.1", "192.168.1.2"})
			},
			expectedRTX: "dhcp relay server 192.168.1.1 192.168.1.2",
		},
		{
			name: "relay_server_max_four",
			buildFunc: func() string {
				return BuildDHCPRelayServerCommand([]string{"10.0.0.1", "10.0.0.2", "10.0.0.3", "10.0.0.4"})
			},
			expectedRTX: "dhcp relay server 10.0.0.1 10.0.0.2 10.0.0.3 10.0.0.4",
		},
		{
			name: "relay_server_truncate_to_four",
			buildFunc: func() string {
				return BuildDHCPRelayServerCommand([]string{"10.0.0.1", "10.0.0.2", "10.0.0.3", "10.0.0.4", "10.0.0.5"})
			},
			expectedRTX: "dhcp relay server 10.0.0.1 10.0.0.2 10.0.0.3 10.0.0.4",
		},
		{
			name: "relay_server_empty",
			buildFunc: func() string {
				return BuildDHCPRelayServerCommand([]string{})
			},
			expectedRTX: "",
		},
		{
			name: "relay_select",
			buildFunc: func() string {
				return BuildDHCPRelaySelectCommand(1, "192.168.1.1")
			},
			expectedRTX: "dhcp relay select 1 192.168.1.1",
		},
		{
			name: "delete_relay_server",
			buildFunc: func() string {
				return BuildDeleteDHCPRelayServerCommand()
			},
			expectedRTX: "no dhcp relay server",
		},
		{
			name: "delete_relay_select",
			buildFunc: func() string {
				return BuildDeleteDHCPRelaySelectCommand(1)
			},
			expectedRTX: "no dhcp relay select 1",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			got := tc.buildFunc()
			if got != tc.expectedRTX {
				t.Errorf("Build() = %q, want %q", got, tc.expectedRTX)
			}
		})
	}
}

// TestDHCPRelayRoundTrip_ParseBuildParse tests full round-trip
func TestDHCPRelayRoundTrip_ParseBuildParse(t *testing.T) {
	parser := NewDHCPRelayParser()

	t.Run("relay_server_round_trip", func(t *testing.T) {
		rtx := "dhcp relay server 192.168.1.1 192.168.1.2"

		// Parse
		config, err := parser.ParseRelayServerConfig(rtx)
		if err != nil {
			t.Fatalf("ParseRelayServerConfig error: %v", err)
		}

		// Build
		rebuilt := BuildDHCPRelayServerCommand(config.Servers)

		// Verify
		if rebuilt != rtx {
			t.Errorf("Round-trip failed:\n  Original: %q\n  Rebuilt:  %q", rtx, rebuilt)
		}
	})

	t.Run("relay_select_round_trip", func(t *testing.T) {
		rtx := "dhcp relay select 1 192.168.1.1"

		// Parse
		configs, err := parser.ParseRelaySelectConfig(rtx)
		if err != nil {
			t.Fatalf("ParseRelaySelectConfig error: %v", err)
		}

		if len(configs) != 1 {
			t.Fatalf("Expected 1 config, got %d", len(configs))
		}

		// Build
		rebuilt := BuildDHCPRelaySelectCommand(configs[0].ScopeID, configs[0].Server)

		// Verify
		if rebuilt != rtx {
			t.Errorf("Round-trip failed:\n  Original: %q\n  Rebuilt:  %q", rtx, rebuilt)
		}
	})
}

// TestDHCPRelayRoundTrip_Validation tests DHCP relay validation functions
func TestDHCPRelayRoundTrip_Validation(t *testing.T) {
	testCases := []struct {
		name      string
		config    DHCPRelayServerConfig
		wantError bool
	}{
		{
			name: "valid_single_server",
			config: DHCPRelayServerConfig{
				Servers: []string{"192.168.1.1"},
			},
			wantError: false,
		},
		{
			name: "valid_four_servers",
			config: DHCPRelayServerConfig{
				Servers: []string{"192.168.1.1", "192.168.1.2", "192.168.1.3", "192.168.1.4"},
			},
			wantError: false,
		},
		{
			name: "valid_empty_servers",
			config: DHCPRelayServerConfig{
				Servers: []string{},
			},
			wantError: false,
		},
		{
			name: "invalid_too_many_servers",
			config: DHCPRelayServerConfig{
				Servers: []string{"10.0.0.1", "10.0.0.2", "10.0.0.3", "10.0.0.4", "10.0.0.5"},
			},
			wantError: true,
		},
		{
			name: "invalid_server_address",
			config: DHCPRelayServerConfig{
				Servers: []string{"invalid"},
			},
			wantError: true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			err := ValidateDHCPRelayServerConfig(tc.config)
			if (err != nil) != tc.wantError {
				t.Errorf("ValidateDHCPRelayServerConfig() error = %v, wantError %v", err, tc.wantError)
			}
		})
	}
}
