// Code generated by specgen. DO NOT EDIT.
// Source: specs/dns_config.yaml
// Command: dns_config
// Reference:

package parsers

import (
	"testing"
)

// TestSpecDNSConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecDNSConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "dns_domain_lookup_on",
			rtxCommand:  `dns domain lookup on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_domain_lookup_off",
			rtxCommand:  `dns domain lookup off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_domain_name",
			rtxCommand:  `dns domain example.com`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_domain_local",
			rtxCommand:  `dns domain local.lan`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_server_single",
			rtxCommand:  `dns server 8.8.8.8`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_server_two",
			rtxCommand:  `dns server 8.8.8.8 8.8.4.4`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_server_three",
			rtxCommand:  `dns server 8.8.8.8 8.8.4.4 1.1.1.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_server_select_simple",
			rtxCommand:  `dns server select 1 8.8.8.8 any .example.com`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_server_select_with_edns",
			rtxCommand:  `dns server select 1 8.8.8.8 edns=on any .example.com`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_server_select_multiple_servers",
			rtxCommand:  `dns server select 1 8.8.8.8 8.8.4.4 any .google.com`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_server_select_record_type_a",
			rtxCommand:  `dns server select 2 1.1.1.1 a .cloudflare.com`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_server_select_restrict_pp",
			rtxCommand:  `dns server select 3 192.168.1.1 any .internal restrict pp 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_static_ipv4",
			rtxCommand:  `dns static server.local 192.168.1.100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_static_router",
			rtxCommand:  `dns static router.local 192.168.1.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_service_recursive",
			rtxCommand:  `dns service recursive`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_service_off",
			rtxCommand:  `dns service off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_private_spoof_on",
			rtxCommand:  `dns private address spoof on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dns_private_spoof_off",
			rtxCommand:  `dns private address spoof off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_dns_server",
			rtxCommand:  `no dns server`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_dns_domain",
			rtxCommand:  `no dns domain`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_dns_server_select",
			rtxCommand:  `no dns server select 1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_dns_static",
			rtxCommand:  `no dns static server.local`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecDNSConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecDNSConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"record_type",
		"server_select_id",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}
