// Code generated by specgen. DO NOT EDIT.
// Source: specs/interface_config.yaml
// Command: interface_config
// Reference:

package parsers

import (
	"testing"
)

// TestSpecInterfaceConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecInterfaceConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "ip_address_cidr",
			rtxCommand:  `ip lan1 address 192.168.1.1/24`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ip_address_cidr_16",
			rtxCommand:  `ip lan2 address 172.16.0.1/16`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ip_address_dhcp",
			rtxCommand:  `ip lan1 address dhcp`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "secure_filter_in",
			rtxCommand:  `ip lan1 secure filter in 1 2 3`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "secure_filter_out",
			rtxCommand:  `ip lan1 secure filter out 100 101 102`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "secure_filter_out_with_dynamic",
			rtxCommand:  `ip lan1 secure filter out 100 101 dynamic 200 201`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "secure_filter_single",
			rtxCommand:  `ip lan2 secure filter in 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ethernet_filter_in",
			rtxCommand:  `ethernet lan1 filter in 1 2`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ethernet_filter_out",
			rtxCommand:  `ethernet lan1 filter out 10`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "nat_descriptor",
			rtxCommand:  `ip lan1 nat descriptor 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "nat_descriptor_100",
			rtxCommand:  `ip lan2 nat descriptor 100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "proxyarp_on",
			rtxCommand:  `ip lan1 proxyarp on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "proxyarp_off",
			rtxCommand:  `ip lan1 proxyarp off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "mtu_1500",
			rtxCommand:  `ip lan1 mtu 1500`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "mtu_1400",
			rtxCommand:  `ip tunnel1 mtu 1400`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "mtu_576",
			rtxCommand:  `ip pp1 mtu 576`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "description_simple",
			rtxCommand:  `description lan1 "Internal Network"`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "description_wan",
			rtxCommand:  `description lan2 "WAN Connection"`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_ip_address",
			rtxCommand:  `no ip lan1 address`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_secure_filter_in",
			rtxCommand:  `no ip lan1 secure filter in`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_secure_filter_out",
			rtxCommand:  `no ip lan1 secure filter out`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_nat_descriptor",
			rtxCommand:  `no ip lan1 nat descriptor`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecInterfaceConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecInterfaceConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"filter_number",
		"mtu",
		"nat_descriptor",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}
