// Code generated by specgen. DO NOT EDIT.
// Source: specs/ip_route.yaml
// Command: ip_route
// Reference: 8.1.7

package parsers

import (
	"testing"
)

// TestSpecIPRouteSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecIPRouteSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "default_route_ip_gateway",
			rtxCommand:  `ip route default gateway 192.168.0.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "default_route_pp",
			rtxCommand:  `ip route default gateway pp 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "default_route_tunnel",
			rtxCommand:  `ip route default gateway tunnel 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "default_route_dhcp_lan",
			rtxCommand:  `ip route default gateway dhcp lan1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "default_route_dhcp_lan2",
			rtxCommand:  `ip route default gateway dhcp lan2`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "default_route_null",
			rtxCommand:  `ip route default gateway null`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_ip_gateway_cidr8",
			rtxCommand:  `ip route 10.0.0.0/8 gateway 192.168.1.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_ip_gateway_cidr16",
			rtxCommand:  `ip route 172.16.0.0/12 gateway 192.168.1.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_ip_gateway_cidr24",
			rtxCommand:  `ip route 192.168.100.0/24 gateway 10.0.0.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_ip_gateway_cidr32",
			rtxCommand:  `ip route 192.168.1.100/32 gateway 192.168.1.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_pp",
			rtxCommand:  `ip route 192.168.1.0/24 gateway pp 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_pp_large_num",
			rtxCommand:  `ip route 192.168.1.0/24 gateway pp 100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_tunnel",
			rtxCommand:  `ip route 10.10.0.0/16 gateway tunnel 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_tunnel_large_num",
			rtxCommand:  `ip route 10.10.0.0/16 gateway tunnel 100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "default_route_with_weight",
			rtxCommand:  `ip route default gateway 192.168.0.1 weight 10`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "default_route_with_weight_zero",
			rtxCommand:  `ip route default gateway 192.168.0.1 weight 0`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_pp_with_weight",
			rtxCommand:  `ip route 192.168.1.0/24 gateway pp 1 weight 2`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_with_filter",
			rtxCommand:  `ip route 10.10.0.0/16 gateway 192.168.1.1 filter 100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_with_filter_min",
			rtxCommand:  `ip route 10.10.0.0/16 gateway 192.168.1.1 filter 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "default_route_pp_with_hide",
			rtxCommand:  `ip route default gateway pp 1 hide`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_tunnel_with_hide",
			rtxCommand:  `ip route 10.0.0.0/8 gateway tunnel 1 hide`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_with_keepalive",
			rtxCommand:  `ip route 10.0.0.0/8 gateway 192.168.1.1 keepalive 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_with_keepalive_large",
			rtxCommand:  `ip route 10.0.0.0/8 gateway 192.168.1.1 keepalive 3000`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_with_metric",
			rtxCommand:  `ip route 10.0.0.0/8 gateway 192.168.1.1 metric 5`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_with_metric_max",
			rtxCommand:  `ip route 10.0.0.0/8 gateway 192.168.1.1 metric 15`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "network_route_with_dpi",
			rtxCommand:  `ip route default gateway pp 1 dpi 1 gateway tunnel 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "route_with_weight_and_filter",
			rtxCommand:  `ip route 10.0.0.0/8 gateway 192.168.1.1 weight 20 filter 50`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "route_with_weight_and_hide",
			rtxCommand:  `ip route default gateway pp 1 weight 2 hide`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "route_with_all_options",
			rtxCommand:  `ip route 10.0.0.0/8 gateway 192.168.1.1 weight 20 filter 50 keepalive 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "multi_gateway_single_line_ecmp_2",
			rtxCommand:  `ip route 10.0.0.0/8 gateway 192.168.1.1 weight 1 gateway 192.168.2.1 weight 2`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "multi_gateway_single_line_ecmp_3",
			rtxCommand:  `ip route 192.168.100.0/24 gateway 10.0.0.1 weight 1 gateway 10.0.0.2 weight 2 gateway 10.0.0.3 weight 3`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "multi_gateway_single_line_failover_pp",
			rtxCommand:  `ip route default gateway pp 1 hide gateway pp 2 weight 0`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "multi_gateway_single_line_pp_with_weight_hide",
			rtxCommand:  `ip route default gateway pp 1 weight 2 hide gateway pp 2 weight 1 hide`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "multi_gateway_single_line_mixed_ip_tunnel",
			rtxCommand:  `ip route 10.0.0.0/8 gateway 192.168.1.1 gateway tunnel 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name: "multi_gateway_multi_line_ecmp_2",
			rtxCommand: `ip route 10.0.0.0/8 gateway 192.168.1.1 weight 1
ip route 10.0.0.0/8 gateway 192.168.2.1 weight 2
`,
			parseOnly:   true,
			buildOnly:   false,
			description: "",
		},
		{
			name: "multi_gateway_multi_line_ecmp_3",
			rtxCommand: `ip route 192.168.100.0/24 gateway 10.0.0.1 weight 1
ip route 192.168.100.0/24 gateway 10.0.0.2 weight 2
ip route 192.168.100.0/24 gateway 10.0.0.3 weight 3
`,
			parseOnly:   true,
			buildOnly:   false,
			description: "",
		},
		{
			name: "multi_gateway_multi_line_failover_pp",
			rtxCommand: `ip route default gateway pp 1 hide
ip route default gateway pp 2 weight 0
`,
			parseOnly:   true,
			buildOnly:   false,
			description: "",
		},
		{
			name: "multi_gateway_multi_line_mixed_types",
			rtxCommand: `ip route 172.16.0.0/12 gateway 192.168.1.1
ip route 172.16.0.0/12 gateway pp 1 hide
ip route 172.16.0.0/12 gateway tunnel 1
`,
			parseOnly:   true,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_default_route",
			rtxCommand:  `no ip route default`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_network_route",
			rtxCommand:  `no ip route 10.0.0.0/8`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_route_specific_gateway",
			rtxCommand:  `no ip route 10.0.0.0/8 gateway 192.168.1.1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_route_specific_pp",
			rtxCommand:  `no ip route 172.16.0.0/12 gateway pp 1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecIPRouteBoundaryCoverage documents the boundary values covered by this spec
func TestSpecIPRouteBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"filter",
		"keepalive",
		"metric",
		"peer_num",
		"prefix_length",
		"tunnel_num",
		"weight",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}

// TestSpecIPRouteModelCompatibility tests router model compatibility
func TestSpecIPRouteModelCompatibility(t *testing.T) {
	// All known RTX router models
	allModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
		"RTX810",
		"NVR700W",
		"NVR510",
		"NVR500",
	}

	// Models that support this command according to the spec
	supportedModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
	}

	// Build a map for quick lookup
	supportedMap := make(map[string]bool)
	for _, m := range supportedModels {
		supportedMap[m] = true
	}

	// Find unsupported models
	var unsupportedModels []string
	for _, m := range allModels {
		if !supportedMap[m] {
			unsupportedModels = append(unsupportedModels, m)
		}
	}

	t.Logf("Command: ip_route")
	t.Logf("Supported models (%d): %v", len(supportedModels), supportedModels)
	t.Logf("Unsupported models (%d): %v", len(unsupportedModels), unsupportedModels)

	// Test: Verify supported models are recognized
	for _, model := range supportedModels {
		t.Run("supported_"+model, func(t *testing.T) {
			if !IsModelSupported("ip_route", model) {
				t.Errorf("Model %s should be supported for ip_route", model)
			}
		})
	}

	// Test: Verify unsupported models are rejected
	for _, model := range unsupportedModels {
		t.Run("unsupported_"+model, func(t *testing.T) {
			if IsModelSupported("ip_route", model) {
				t.Errorf("Model %s should NOT be supported for ip_route", model)
			}
		})
	}
}
