// Code generated by specgen. DO NOT EDIT.
// Source: specs/ipv6_config.yaml
// Command: ipv6_config
// Reference:

package parsers

import (
	"testing"
)

// TestSpecIpv6ConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecIpv6ConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "ipv6_address_static",
			rtxCommand:  `ipv6 lan1 address 2001:db8::1/64`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipv6_address_link_local",
			rtxCommand:  `ipv6 lan1 address fe80::1/64`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipv6_address_loopback",
			rtxCommand:  `ipv6 loopback1 address 2001:db8:1::1/128`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipv6_address_prefix_based",
			rtxCommand:  `ipv6 lan1 address 1::1/64`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "rtadv_basic",
			rtxCommand:  `ipv6 lan1 rtadv send 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "rtadv_with_o_flag",
			rtxCommand:  `ipv6 lan1 rtadv send 1 o_flag=on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "rtadv_with_m_flag",
			rtxCommand:  `ipv6 lan1 rtadv send 1 m_flag=on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "rtadv_with_lifetime",
			rtxCommand:  `ipv6 lan1 rtadv send 1 lifetime=1800`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "rtadv_full",
			rtxCommand:  `ipv6 lan1 rtadv send 1 o_flag=on m_flag=off lifetime=3600`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dhcpv6_server",
			rtxCommand:  `ipv6 lan1 dhcp service server`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "dhcpv6_client",
			rtxCommand:  `ipv6 lan1 dhcp service client`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipv6_mtu",
			rtxCommand:  `ipv6 lan1 mtu 1500`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipv6_mtu_1280",
			rtxCommand:  `ipv6 tunnel1 mtu 1280`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipv6_secure_filter_in",
			rtxCommand:  `ipv6 lan1 secure filter in 1 2 3`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipv6_secure_filter_out",
			rtxCommand:  `ipv6 lan1 secure filter out 100 101`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipv6_secure_filter_out_dynamic",
			rtxCommand:  `ipv6 lan1 secure filter out 100 dynamic 200`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "prefix_static",
			rtxCommand:  `ipv6 prefix 1 2001:db8::/48`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "prefix_ra",
			rtxCommand:  `ipv6 prefix 2 ra-prefix@pp1::/64`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "prefix_dhcpv6_pd",
			rtxCommand:  `ipv6 prefix 3 dhcp-prefix@lan2::/56`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_ipv6_address",
			rtxCommand:  `no ipv6 lan1 address`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_ipv6_address_specific",
			rtxCommand:  `no ipv6 lan1 address 2001:db8::1/64`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_rtadv",
			rtxCommand:  `no ipv6 lan1 rtadv send`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_prefix",
			rtxCommand:  `no ipv6 prefix 1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecIpv6ConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecIpv6ConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"mtu",
		"prefix_id",
		"prefix_length",
		"router_lifetime",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}
