// Code generated by specgen. DO NOT EDIT.
// Source: specs/nat_static.yaml
// Command: nat_static
// Reference:

package parsers

import (
	"testing"
)

// TestSpecNatStaticSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecNatStaticSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "nat_type_static",
			rtxCommand:  `nat descriptor type 1 static`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "nat_type_static_100",
			rtxCommand:  `nat descriptor type 100 static`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "nat_static_1to1",
			rtxCommand:  `nat descriptor static 1 203.0.113.10=192.168.1.10`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "nat_static_1to1_second",
			rtxCommand:  `nat descriptor static 1 203.0.113.11=192.168.1.11`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "nat_static_multiple_desc",
			rtxCommand:  `nat descriptor static 2 10.0.0.100=172.16.0.100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "nat_static_port_tcp",
			rtxCommand:  `nat descriptor static 1 203.0.113.10:80=192.168.1.10:80 tcp`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "nat_static_port_tcp_https",
			rtxCommand:  `nat descriptor static 1 203.0.113.10:443=192.168.1.10:443 tcp`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "nat_static_port_udp",
			rtxCommand:  `nat descriptor static 1 203.0.113.10:53=192.168.1.10:53 udp`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "nat_static_port_different",
			rtxCommand:  `nat descriptor static 1 203.0.113.10:8080=192.168.1.10:80 tcp`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "interface_nat_static",
			rtxCommand:  `ip lan2 nat descriptor 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_nat_static",
			rtxCommand:  `no nat descriptor type 1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_nat_static_mapping",
			rtxCommand:  `no nat descriptor static 1 203.0.113.10=192.168.1.10`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_nat_static_port_mapping",
			rtxCommand:  `no nat descriptor static 1 203.0.113.10:80=192.168.1.10:80 tcp`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecNatStaticBoundaryCoverage documents the boundary values covered by this spec
func TestSpecNatStaticBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"descriptor_id",
		"port",
		"protocol",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}
