// Code generated by specgen. DO NOT EDIT.
// Source: specs/service_config.yaml
// Command: service_config
// Reference:

package parsers

import (
	"testing"
)

// TestSpecServiceConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecServiceConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "httpd_host_any",
			rtxCommand:  `httpd host any`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "httpd_host_lan1",
			rtxCommand:  `httpd host lan1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "httpd_host_lan2",
			rtxCommand:  `httpd host lan2`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "httpd_proxy_access_on",
			rtxCommand:  `httpd proxy-access l2ms permit on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "httpd_proxy_access_off",
			rtxCommand:  `httpd proxy-access l2ms permit off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "sshd_service_on",
			rtxCommand:  `sshd service on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "sshd_service_off",
			rtxCommand:  `sshd service off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "sshd_host_single",
			rtxCommand:  `sshd host lan1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "sshd_host_multiple",
			rtxCommand:  `sshd host lan1 lan2`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "sshd_host_any",
			rtxCommand:  `sshd host any`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "sshd_auth_password",
			rtxCommand:  `sshd auth method password`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "sshd_auth_publickey",
			rtxCommand:  `sshd auth method publickey`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "sshd_host_key_generate",
			rtxCommand:  `sshd host key generate`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "sftpd_host_single",
			rtxCommand:  `sftpd host lan1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "sftpd_host_multiple",
			rtxCommand:  `sftpd host lan1 lan2`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_httpd_host",
			rtxCommand:  `no httpd host`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_sshd_service",
			rtxCommand:  `no sshd service`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_sshd_host",
			rtxCommand:  `no sshd host`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_sftpd_host",
			rtxCommand:  `no sftpd host`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecServiceConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecServiceConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"auth_method",
		"host",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}
