// Code generated by specgen. DO NOT EDIT.
// Source: specs/syslog_config.yaml
// Command: syslog_config
// Reference:

package parsers

import (
	"encoding/json"
	"strings"
	"testing"
)

// TestSpecSyslogConfigRTXSyntax validates that RTX commands in spec are well-formed
func TestSpecSyslogConfigRTXSyntax(t *testing.T) {
	// This test validates that all RTX command strings in the spec are well-formed
	// and follow expected patterns

	testCases := []struct {
		name       string
		rtxCommand string
		parseOnly  bool
		buildOnly  bool
	}{
		{
			name:       "syslog_host",
			rtxCommand: `syslog host 192.168.1.100`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_host_with_port",
			rtxCommand: `syslog host 192.168.1.100 514`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_host_custom_port",
			rtxCommand: `syslog host 10.0.0.50 1514`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_host_ipv6",
			rtxCommand: `syslog host 2001:db8::100`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_local_address",
			rtxCommand: `syslog local address 192.168.1.1`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_local_address_loopback",
			rtxCommand: `syslog local address 10.0.0.1`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_facility_user",
			rtxCommand: `syslog facility user`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_facility_local0",
			rtxCommand: `syslog facility local0`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_facility_local7",
			rtxCommand: `syslog facility local7`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_notice_on",
			rtxCommand: `syslog notice on`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_notice_off",
			rtxCommand: `syslog notice off`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_info_on",
			rtxCommand: `syslog info on`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_info_off",
			rtxCommand: `syslog info off`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_debug_on",
			rtxCommand: `syslog debug on`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "syslog_debug_off",
			rtxCommand: `syslog debug off`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "delete_syslog_host",
			rtxCommand: `no syslog host 192.168.1.100`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "delete_syslog_local_address",
			rtxCommand: `no syslog local address`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "delete_syslog_facility",
			rtxCommand: `no syslog facility`,
			parseOnly:  false,
			buildOnly:  true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Validate RTX command is not empty
			if strings.TrimSpace(tc.rtxCommand) == "" {
				t.Errorf("RTX command should not be empty")
			}

			// Validate command doesn't have trailing/leading whitespace issues
			trimmed := strings.TrimSpace(tc.rtxCommand)
			if tc.rtxCommand != trimmed && !strings.Contains(tc.rtxCommand, "\n") {
				t.Errorf("RTX command has unexpected whitespace: %q", tc.rtxCommand)
			}

			// Log the command for visibility
			if !tc.buildOnly {
				t.Logf("Parse test: %s", tc.rtxCommand)
			}
			if !tc.parseOnly {
				t.Logf("Build test: %s", tc.rtxCommand)
			}
		})
	}
}

// TestSpecSyslogConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecSyslogConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "syslog_host",
			rtxCommand:  `syslog host 192.168.1.100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_host_with_port",
			rtxCommand:  `syslog host 192.168.1.100 514`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_host_custom_port",
			rtxCommand:  `syslog host 10.0.0.50 1514`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_host_ipv6",
			rtxCommand:  `syslog host 2001:db8::100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_local_address",
			rtxCommand:  `syslog local address 192.168.1.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_local_address_loopback",
			rtxCommand:  `syslog local address 10.0.0.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_facility_user",
			rtxCommand:  `syslog facility user`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_facility_local0",
			rtxCommand:  `syslog facility local0`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_facility_local7",
			rtxCommand:  `syslog facility local7`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_notice_on",
			rtxCommand:  `syslog notice on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_notice_off",
			rtxCommand:  `syslog notice off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_info_on",
			rtxCommand:  `syslog info on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_info_off",
			rtxCommand:  `syslog info off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_debug_on",
			rtxCommand:  `syslog debug on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "syslog_debug_off",
			rtxCommand:  `syslog debug off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_syslog_host",
			rtxCommand:  `no syslog host 192.168.1.100`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_syslog_local_address",
			rtxCommand:  `no syslog local address`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_syslog_facility",
			rtxCommand:  `no syslog facility`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecSyslogConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecSyslogConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"facility",
		"port",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}

// TestSpecSyslogConfigRTXTerraformMapping validates RTX command to Terraform value mappings
func TestSpecSyslogConfigRTXTerraformMapping(t *testing.T) {
	// This test validates that each RTX command has a corresponding expected Terraform value
	// and vice versa. It ensures the spec file correctly documents the bidirectional mapping.

	testCases := []struct {
		name          string
		rtxCommand    string
		terraformJSON string
		parseOnly     bool
		buildOnly     bool
	}{
		{
			name:          "syslog_host",
			rtxCommand:    `syslog host 192.168.1.100`,
			terraformJSON: `{"hosts":[{"address":"192.168.1.100"}]}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_host_with_port",
			rtxCommand:    `syslog host 192.168.1.100 514`,
			terraformJSON: `{"hosts":[{"address":"192.168.1.100","port":514}]}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_host_custom_port",
			rtxCommand:    `syslog host 10.0.0.50 1514`,
			terraformJSON: `{"hosts":[{"address":"10.0.0.50","port":1514}]}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_host_ipv6",
			rtxCommand:    `syslog host 2001:db8::100`,
			terraformJSON: `{"hosts":[{"address":"2001:db8::100"}]}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_local_address",
			rtxCommand:    `syslog local address 192.168.1.1`,
			terraformJSON: `{"local_address":"192.168.1.1"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_local_address_loopback",
			rtxCommand:    `syslog local address 10.0.0.1`,
			terraformJSON: `{"local_address":"10.0.0.1"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_facility_user",
			rtxCommand:    `syslog facility user`,
			terraformJSON: `{"facility":"user"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_facility_local0",
			rtxCommand:    `syslog facility local0`,
			terraformJSON: `{"facility":"local0"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_facility_local7",
			rtxCommand:    `syslog facility local7`,
			terraformJSON: `{"facility":"local7"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_notice_on",
			rtxCommand:    `syslog notice on`,
			terraformJSON: `{"notice":true}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_notice_off",
			rtxCommand:    `syslog notice off`,
			terraformJSON: `{"notice":false}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_info_on",
			rtxCommand:    `syslog info on`,
			terraformJSON: `{"info":true}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_info_off",
			rtxCommand:    `syslog info off`,
			terraformJSON: `{"info":false}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_debug_on",
			rtxCommand:    `syslog debug on`,
			terraformJSON: `{"debug":true}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "syslog_debug_off",
			rtxCommand:    `syslog debug off`,
			terraformJSON: `{"debug":false}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "delete_syslog_host",
			rtxCommand:    `no syslog host 192.168.1.100`,
			terraformJSON: `{"address":"192.168.1.100"}`,
			parseOnly:     false,
			buildOnly:     true,
		},
		{
			name:          "delete_syslog_local_address",
			rtxCommand:    `no syslog local address`,
			terraformJSON: `{}`,
			parseOnly:     false,
			buildOnly:     true,
		},
		{
			name:          "delete_syslog_facility",
			rtxCommand:    `no syslog facility`,
			terraformJSON: `{}`,
			parseOnly:     false,
			buildOnly:     true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Validate RTX command is not empty
			if strings.TrimSpace(tc.rtxCommand) == "" {
				t.Errorf("RTX command should not be empty")
				return
			}

			// build_only tests (like delete commands) may have empty terraform values
			// because they represent commands that don't have a direct terraform mapping
			if tc.buildOnly {
				t.Logf("Direction: Terraform -> RTX only (build)")
				t.Logf("RTX: %s", tc.rtxCommand)
				t.Logf("Terraform: %s (build_only, may be empty)", tc.terraformJSON)
				return
			}

			// Validate terraform JSON is present and valid for non-build_only tests
			if tc.terraformJSON == "null" || tc.terraformJSON == "" {
				t.Errorf("Terraform value is missing for RTX command: %s", tc.rtxCommand)
				return
			}

			var tfValue interface{}
			if err := json.Unmarshal([]byte(tc.terraformJSON), &tfValue); err != nil {
				t.Errorf("Invalid terraform JSON: %v\nJSON: %s", err, tc.terraformJSON)
				return
			}

			// Log the mapping for visibility
			t.Logf("RTX: %s", tc.rtxCommand)
			t.Logf("Terraform: %s", tc.terraformJSON)

			// Validate that terraform value contains expected fields (only for non-build_only tests)
			if tfMap, ok := tfValue.(map[string]interface{}); ok {
				if len(tfMap) == 0 {
					t.Errorf("Terraform value is empty map for RTX command: %s", tc.rtxCommand)
					return
				}
			}

			// Check mapping direction
			if tc.parseOnly {
				t.Logf("Direction: RTX -> Terraform only (parse)")
			} else {
				t.Logf("Direction: Bidirectional (parse and build)")
			}
		})
	}
}

// TestSpecSyslogConfigModelCompatibility tests router model compatibility
func TestSpecSyslogConfigModelCompatibility(t *testing.T) {
	// All known RTX router models
	allModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
		"RTX810",
		"NVR700W",
		"NVR510",
		"NVR500",
	}

	// Models that support this command according to the spec
	supportedModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
	}

	// Build a map for quick lookup
	supportedMap := make(map[string]bool)
	for _, m := range supportedModels {
		supportedMap[m] = true
	}

	// Find unsupported models
	var unsupportedModels []string
	for _, m := range allModels {
		if !supportedMap[m] {
			unsupportedModels = append(unsupportedModels, m)
		}
	}

	t.Logf("Command: syslog_config")
	t.Logf("Supported models (%d): %v", len(supportedModels), supportedModels)
	t.Logf("Unsupported models (%d): %v", len(unsupportedModels), unsupportedModels)

	// Test: Verify supported models are recognized
	for _, model := range supportedModels {
		t.Run("supported_"+model, func(t *testing.T) {
			if !IsModelSupported("syslog_config", model) {
				t.Errorf("Model %s should be supported for syslog_config", model)
			}
		})
	}

	// Test: Verify unsupported models are rejected
	for _, model := range unsupportedModels {
		t.Run("unsupported_"+model, func(t *testing.T) {
			if IsModelSupported("syslog_config", model) {
				t.Errorf("Model %s should NOT be supported for syslog_config", model)
			}
		})
	}
}
