// Code generated by specgen. DO NOT EDIT.
// Source: specs/system_config.yaml
// Command: system_config
// Reference:

package parsers

import (
	"testing"
)

// TestSpecSystemConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecSystemConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "timezone_jst",
			rtxCommand:  `timezone +09:00`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "timezone_utc",
			rtxCommand:  `timezone +00:00`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "timezone_negative",
			rtxCommand:  `timezone -05:00`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "timezone_negative_large",
			rtxCommand:  `timezone -12:00`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "timezone_positive_large",
			rtxCommand:  `timezone +14:00`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_character_utf8",
			rtxCommand:  `console character ja.utf8`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_character_sjis",
			rtxCommand:  `console character ja.sjis`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_character_ascii",
			rtxCommand:  `console character ascii`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_character_eucjp",
			rtxCommand:  `console character euc-jp`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_lines_24",
			rtxCommand:  `console lines 24`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_lines_50",
			rtxCommand:  `console lines 50`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_lines_100",
			rtxCommand:  `console lines 100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_lines_infinity",
			rtxCommand:  `console lines infinity`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_prompt_simple",
			rtxCommand:  `console prompt router`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_prompt_with_spaces",
			rtxCommand:  `console prompt "RTX Router"`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "console_prompt_hostname",
			rtxCommand:  `console prompt rtx1300`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "packet_buffer_small",
			rtxCommand:  `system packet-buffer small max-buffer=5000 max-free=1300`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "packet_buffer_middle",
			rtxCommand:  `system packet-buffer middle max-buffer=3000 max-free=800`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "packet_buffer_large",
			rtxCommand:  `system packet-buffer large max-buffer=1000 max-free=200`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "packet_buffer_small_large_values",
			rtxCommand:  `system packet-buffer small max-buffer=10000 max-free=5000`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "statistics_traffic_on",
			rtxCommand:  `statistics traffic on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "statistics_traffic_off",
			rtxCommand:  `statistics traffic off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "statistics_nat_on",
			rtxCommand:  `statistics nat on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "statistics_nat_off",
			rtxCommand:  `statistics nat off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_timezone",
			rtxCommand:  `no timezone`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_console_character",
			rtxCommand:  `no console character`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_console_lines",
			rtxCommand:  `no console lines`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_console_prompt",
			rtxCommand:  `no console prompt`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_packet_buffer_small",
			rtxCommand:  `no system packet-buffer small`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_statistics_traffic",
			rtxCommand:  `no statistics traffic`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_statistics_nat",
			rtxCommand:  `no statistics nat`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name: "full_system_config",
			rtxCommand: `timezone +09:00
console character ja.utf8
console lines 50
console prompt "RTX Router"
system packet-buffer small max-buffer=5000 max-free=1300
system packet-buffer middle max-buffer=3000 max-free=800
statistics traffic on
statistics nat on
`,
			parseOnly:   true,
			buildOnly:   false,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecSystemConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecSystemConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"character_encoding",
		"console_lines",
		"max_buffer",
		"max_free",
		"packet_buffer_size",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}

// TestSpecSystemConfigModelCompatibility tests router model compatibility
func TestSpecSystemConfigModelCompatibility(t *testing.T) {
	// All known RTX router models
	allModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
		"RTX810",
		"NVR700W",
		"NVR510",
		"NVR500",
	}

	// Models that support this command according to the spec
	supportedModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
	}

	// Build a map for quick lookup
	supportedMap := make(map[string]bool)
	for _, m := range supportedModels {
		supportedMap[m] = true
	}

	// Find unsupported models
	var unsupportedModels []string
	for _, m := range allModels {
		if !supportedMap[m] {
			unsupportedModels = append(unsupportedModels, m)
		}
	}

	t.Logf("Command: system_config")
	t.Logf("Supported models (%d): %v", len(supportedModels), supportedModels)
	t.Logf("Unsupported models (%d): %v", len(unsupportedModels), unsupportedModels)

	// Test: Verify supported models are recognized
	for _, model := range supportedModels {
		t.Run("supported_"+model, func(t *testing.T) {
			if !IsModelSupported("system_config", model) {
				t.Errorf("Model %s should be supported for system_config", model)
			}
		})
	}

	// Test: Verify unsupported models are rejected
	for _, model := range unsupportedModels {
		t.Run("unsupported_"+model, func(t *testing.T) {
			if IsModelSupported("system_config", model) {
				t.Errorf("Model %s should NOT be supported for system_config", model)
			}
		})
	}
}
