// Code generated by specgen. DO NOT EDIT.
// Source: specs/tunnel_config.yaml
// Command: tunnel_config
// Reference:

package parsers

import (
	"testing"
)

// TestSpecTunnelConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecTunnelConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "tunnel_select_1",
			rtxCommand:  `tunnel select 1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "tunnel_select_100",
			rtxCommand:  `tunnel select 100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "tunnel_encapsulation_ipsec",
			rtxCommand:  `tunnel encapsulation ipsec`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "tunnel_encapsulation_l2tp",
			rtxCommand:  `tunnel encapsulation l2tp`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "tunnel_encapsulation_l2tpv3",
			rtxCommand:  `tunnel encapsulation l2tpv3`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "tunnel_endpoint_name",
			rtxCommand:  `tunnel endpoint name vpn.example.com fqdn`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "tunnel_endpoint_name_ip",
			rtxCommand:  `tunnel endpoint name 203.0.113.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "tunnel_endpoint_address",
			rtxCommand:  `tunnel endpoint address 192.168.1.1 203.0.113.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "tunnel_description",
			rtxCommand:  `description "VPN to Branch Office"`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "tunnel_description_simple",
			rtxCommand:  `description Site-to-Site-VPN`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "tunnel_enable",
			rtxCommand:  `tunnel enable 1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "tunnel_disable",
			rtxCommand:  `tunnel disable 1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "ipsec_ike_local_address",
			rtxCommand:  `ipsec ike local address 1 192.168.1.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipsec_ike_remote_address",
			rtxCommand:  `ipsec ike remote address 1 203.0.113.1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipsec_ike_psk",
			rtxCommand:  `ipsec ike pre-shared-key 1 text mysecret`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipsec_ike_nat_traversal_on",
			rtxCommand:  `ipsec ike nat-traversal 1 on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipsec_ike_nat_traversal_off",
			rtxCommand:  `ipsec ike nat-traversal 1 off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipsec_ike_keepalive_log_on",
			rtxCommand:  `ipsec ike keepalive log 1 on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "ipsec_ike_keepalive_log_off",
			rtxCommand:  `ipsec ike keepalive log 1 off`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "l2tp_hostname",
			rtxCommand:  `l2tp hostname myrouter`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "l2tp_always_on",
			rtxCommand:  `l2tp always-on on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "l2tp_syslog_on",
			rtxCommand:  `l2tp syslog on`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "delete_tunnel",
			rtxCommand:  `no tunnel select 1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecTunnelConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecTunnelConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"encapsulation",
		"endpoint_name_type",
		"tunnel_id",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}
