// Code generated by specgen. DO NOT EDIT.
// Source: specs/vlan_config.yaml
// Command: vlan_config
// Reference:

package parsers

import (
	"testing"
)

// TestSpecVlanConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecVlanConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "vlan_create_basic",
			rtxCommand:  `vlan lan1/1 802.1q vid=100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_create_vid_200",
			rtxCommand:  `vlan lan1/2 802.1q vid=200`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_create_lan2",
			rtxCommand:  `vlan lan2/1 802.1q vid=10`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_create_vid_1",
			rtxCommand:  `vlan lan1/3 802.1q vid=1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_create_vid_4094",
			rtxCommand:  `vlan lan1/4 802.1q vid=4094`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_ip_address_cidr",
			rtxCommand:  `ip lan1/1 address 192.168.100.1/24`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_ip_address_16",
			rtxCommand:  `ip lan1/2 address 172.16.0.1/16`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_ip_address_dotted",
			rtxCommand:  `ip lan1/3 address 10.0.0.1 255.255.255.0`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_description",
			rtxCommand:  `description lan1/1 "Management VLAN"`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_description_simple",
			rtxCommand:  `description lan1/2 Server-VLAN`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_description_guest",
			rtxCommand:  `description lan1/3 "Guest Network"`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_enable",
			rtxCommand:  `lan1/1 enable`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "vlan_disable",
			rtxCommand:  `no lan1/1 enable`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_vlan",
			rtxCommand:  `no vlan lan1/1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_vlan_ip",
			rtxCommand:  `no ip lan1/1 address`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_vlan_description",
			rtxCommand:  `no description lan1/1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecVlanConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecVlanConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"interface",
		"slot",
		"vlan_id",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}

// TestSpecVlanConfigModelCompatibility tests router model compatibility
func TestSpecVlanConfigModelCompatibility(t *testing.T) {
	// All known RTX router models
	allModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
		"RTX810",
		"NVR700W",
		"NVR510",
		"NVR500",
	}

	// Models that support this command according to the spec
	supportedModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
	}

	// Build a map for quick lookup
	supportedMap := make(map[string]bool)
	for _, m := range supportedModels {
		supportedMap[m] = true
	}

	// Find unsupported models
	var unsupportedModels []string
	for _, m := range allModels {
		if !supportedMap[m] {
			unsupportedModels = append(unsupportedModels, m)
		}
	}

	t.Logf("Command: vlan_config")
	t.Logf("Supported models (%d): %v", len(supportedModels), supportedModels)
	t.Logf("Unsupported models (%d): %v", len(unsupportedModels), unsupportedModels)

	// Test: Verify supported models are recognized
	for _, model := range supportedModels {
		t.Run("supported_"+model, func(t *testing.T) {
			if !IsModelSupported("vlan_config", model) {
				t.Errorf("Model %s should be supported for vlan_config", model)
			}
		})
	}

	// Test: Verify unsupported models are rejected
	for _, model := range unsupportedModels {
		t.Run("unsupported_"+model, func(t *testing.T) {
			if IsModelSupported("vlan_config", model) {
				t.Errorf("Model %s should NOT be supported for vlan_config", model)
			}
		})
	}
}
