// Code generated by specgen. DO NOT EDIT.
// Source: specs/vlan_config.yaml
// Command: vlan_config
// Reference:

package parsers

import (
	"encoding/json"
	"strings"
	"testing"
)

// TestSpecVlanConfigRTXSyntax validates that RTX commands in spec are well-formed
func TestSpecVlanConfigRTXSyntax(t *testing.T) {
	// This test validates that all RTX command strings in the spec are well-formed
	// and follow expected patterns

	testCases := []struct {
		name       string
		rtxCommand string
		parseOnly  bool
		buildOnly  bool
	}{
		{
			name:       "vlan_create_basic",
			rtxCommand: `vlan lan1/1 802.1q vid=100`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_create_vid_200",
			rtxCommand: `vlan lan1/2 802.1q vid=200`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_create_lan2",
			rtxCommand: `vlan lan2/1 802.1q vid=10`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_create_vid_1",
			rtxCommand: `vlan lan1/3 802.1q vid=1`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_create_vid_4094",
			rtxCommand: `vlan lan1/4 802.1q vid=4094`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_ip_address_cidr",
			rtxCommand: `ip lan1/1 address 192.168.100.1/24`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_ip_address_16",
			rtxCommand: `ip lan1/2 address 172.16.0.1/16`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_ip_address_dotted",
			rtxCommand: `ip lan1/3 address 10.0.0.1 255.255.255.0`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_description",
			rtxCommand: `description lan1/1 "Management VLAN"`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_description_simple",
			rtxCommand: `description lan1/2 Server-VLAN`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_description_guest",
			rtxCommand: `description lan1/3 "Guest Network"`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_enable",
			rtxCommand: `lan1/1 enable`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "vlan_disable",
			rtxCommand: `no lan1/1 enable`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "delete_vlan",
			rtxCommand: `no vlan lan1/1`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "delete_vlan_ip",
			rtxCommand: `no ip lan1/1 address`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "delete_vlan_description",
			rtxCommand: `no description lan1/1`,
			parseOnly:  false,
			buildOnly:  true,
		},
		{
			name:       "vlan_id_min",
			rtxCommand: `vlan lan1/1 802.1q vid=1`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_id_max",
			rtxCommand: `vlan lan1/1 802.1q vid=4094`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_port_2",
			rtxCommand: `vlan lan1/2 802.1q vid=100`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_port_3",
			rtxCommand: `vlan lan1/3 802.1q vid=200`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_lan2",
			rtxCommand: `vlan lan2/1 802.1q vid=500`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_ip_address",
			rtxCommand: `ip vlan1 address 192.168.10.1/24`,
			parseOnly:  false,
			buildOnly:  false,
		},
		{
			name:       "vlan_ip_address_2",
			rtxCommand: `ip vlan2 address 192.168.20.1/24`,
			parseOnly:  false,
			buildOnly:  false,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Validate RTX command is not empty
			if strings.TrimSpace(tc.rtxCommand) == "" {
				t.Errorf("RTX command should not be empty")
			}

			// Validate command doesn't have trailing/leading whitespace issues
			trimmed := strings.TrimSpace(tc.rtxCommand)
			if tc.rtxCommand != trimmed && !strings.Contains(tc.rtxCommand, "\n") {
				t.Errorf("RTX command has unexpected whitespace: %q", tc.rtxCommand)
			}

			// Log the command for visibility
			if !tc.buildOnly {
				t.Logf("Parse test: %s", tc.rtxCommand)
			}
			if !tc.parseOnly {
				t.Logf("Build test: %s", tc.rtxCommand)
			}
		})
	}
}

// TestSpecVlanConfigSyntaxCoverage documents the syntax patterns covered by this spec
func TestSpecVlanConfigSyntaxCoverage(t *testing.T) {
	// This test documents all syntax patterns defined in the spec
	// Each pattern should have corresponding implementation in the parser

	syntaxPatterns := []struct {
		name        string
		rtxCommand  string
		parseOnly   bool
		buildOnly   bool
		description string
	}{
		{
			name:        "vlan_create_basic",
			rtxCommand:  `vlan lan1/1 802.1q vid=100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_create_vid_200",
			rtxCommand:  `vlan lan1/2 802.1q vid=200`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_create_lan2",
			rtxCommand:  `vlan lan2/1 802.1q vid=10`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_create_vid_1",
			rtxCommand:  `vlan lan1/3 802.1q vid=1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_create_vid_4094",
			rtxCommand:  `vlan lan1/4 802.1q vid=4094`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_ip_address_cidr",
			rtxCommand:  `ip lan1/1 address 192.168.100.1/24`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_ip_address_16",
			rtxCommand:  `ip lan1/2 address 172.16.0.1/16`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_ip_address_dotted",
			rtxCommand:  `ip lan1/3 address 10.0.0.1 255.255.255.0`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_description",
			rtxCommand:  `description lan1/1 "Management VLAN"`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_description_simple",
			rtxCommand:  `description lan1/2 Server-VLAN`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_description_guest",
			rtxCommand:  `description lan1/3 "Guest Network"`,
			parseOnly:   false,
			buildOnly:   false,
			description: "",
		},
		{
			name:        "vlan_enable",
			rtxCommand:  `lan1/1 enable`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "vlan_disable",
			rtxCommand:  `no lan1/1 enable`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_vlan",
			rtxCommand:  `no vlan lan1/1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_vlan_ip",
			rtxCommand:  `no ip lan1/1 address`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "delete_vlan_description",
			rtxCommand:  `no description lan1/1`,
			parseOnly:   false,
			buildOnly:   true,
			description: "",
		},
		{
			name:        "vlan_id_min",
			rtxCommand:  `vlan lan1/1 802.1q vid=1`,
			parseOnly:   false,
			buildOnly:   false,
			description: "VLAN ID最小",
		},
		{
			name:        "vlan_id_max",
			rtxCommand:  `vlan lan1/1 802.1q vid=4094`,
			parseOnly:   false,
			buildOnly:   false,
			description: "VLAN ID最大",
		},
		{
			name:        "vlan_port_2",
			rtxCommand:  `vlan lan1/2 802.1q vid=100`,
			parseOnly:   false,
			buildOnly:   false,
			description: "ポート2",
		},
		{
			name:        "vlan_port_3",
			rtxCommand:  `vlan lan1/3 802.1q vid=200`,
			parseOnly:   false,
			buildOnly:   false,
			description: "ポート3",
		},
		{
			name:        "vlan_lan2",
			rtxCommand:  `vlan lan2/1 802.1q vid=500`,
			parseOnly:   false,
			buildOnly:   false,
			description: "LAN2ポート",
		},
		{
			name:        "vlan_ip_address",
			rtxCommand:  `ip vlan1 address 192.168.10.1/24`,
			parseOnly:   false,
			buildOnly:   false,
			description: "VLANアドレス",
		},
		{
			name:        "vlan_ip_address_2",
			rtxCommand:  `ip vlan2 address 192.168.20.1/24`,
			parseOnly:   false,
			buildOnly:   false,
			description: "VLAN2アドレス",
		},
	}

	t.Logf("Total syntax patterns: %d", len(syntaxPatterns))

	parseOnlyCount := 0
	buildOnlyCount := 0
	bidirectionalCount := 0

	for _, p := range syntaxPatterns {
		if p.parseOnly {
			parseOnlyCount++
		} else if p.buildOnly {
			buildOnlyCount++
		} else {
			bidirectionalCount++
		}
	}

	t.Logf("Parse-only patterns: %d", parseOnlyCount)
	t.Logf("Build-only patterns: %d", buildOnlyCount)
	t.Logf("Bidirectional patterns: %d", bidirectionalCount)
}

// TestSpecVlanConfigBoundaryCoverage documents the boundary values covered by this spec
func TestSpecVlanConfigBoundaryCoverage(t *testing.T) {
	// This test documents all boundary value tests defined in the spec
	boundaryParams := []string{
		"interface",
		"slot",
		"vlan_id",
	}

	t.Logf("Parameters with boundary tests: %d", len(boundaryParams))
	for _, param := range boundaryParams {
		t.Logf("  - %s", param)
	}
}

// TestSpecVlanConfigRTXTerraformMapping validates RTX command to Terraform value mappings
func TestSpecVlanConfigRTXTerraformMapping(t *testing.T) {
	// This test validates that each RTX command has a corresponding expected Terraform value
	// and vice versa. It ensures the spec file correctly documents the bidirectional mapping.

	testCases := []struct {
		name          string
		rtxCommand    string
		terraformJSON string
		parseOnly     bool
		buildOnly     bool
	}{
		{
			name:          "vlan_create_basic",
			rtxCommand:    `vlan lan1/1 802.1q vid=100`,
			terraformJSON: `{"interface":"lan1","slot":1,"vlan_id":100}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_create_vid_200",
			rtxCommand:    `vlan lan1/2 802.1q vid=200`,
			terraformJSON: `{"interface":"lan1","slot":2,"vlan_id":200}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_create_lan2",
			rtxCommand:    `vlan lan2/1 802.1q vid=10`,
			terraformJSON: `{"interface":"lan2","slot":1,"vlan_id":10}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_create_vid_1",
			rtxCommand:    `vlan lan1/3 802.1q vid=1`,
			terraformJSON: `{"interface":"lan1","slot":3,"vlan_id":1}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_create_vid_4094",
			rtxCommand:    `vlan lan1/4 802.1q vid=4094`,
			terraformJSON: `{"interface":"lan1","slot":4,"vlan_id":4094}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_ip_address_cidr",
			rtxCommand:    `ip lan1/1 address 192.168.100.1/24`,
			terraformJSON: `{"ip_address":"192.168.100.1","ip_mask":"255.255.255.0","vlan_interface":"lan1/1"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_ip_address_16",
			rtxCommand:    `ip lan1/2 address 172.16.0.1/16`,
			terraformJSON: `{"ip_address":"172.16.0.1","ip_mask":"255.255.0.0","vlan_interface":"lan1/2"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_ip_address_dotted",
			rtxCommand:    `ip lan1/3 address 10.0.0.1 255.255.255.0`,
			terraformJSON: `{"ip_address":"10.0.0.1","ip_mask":"255.255.255.0","vlan_interface":"lan1/3"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_description",
			rtxCommand:    `description lan1/1 "Management VLAN"`,
			terraformJSON: `{"name":"Management VLAN","vlan_interface":"lan1/1"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_description_simple",
			rtxCommand:    `description lan1/2 Server-VLAN`,
			terraformJSON: `{"name":"Server-VLAN","vlan_interface":"lan1/2"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_description_guest",
			rtxCommand:    `description lan1/3 "Guest Network"`,
			terraformJSON: `{"name":"Guest Network","vlan_interface":"lan1/3"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_enable",
			rtxCommand:    `lan1/1 enable`,
			terraformJSON: `{"shutdown":false,"vlan_interface":"lan1/1"}`,
			parseOnly:     false,
			buildOnly:     true,
		},
		{
			name:          "vlan_disable",
			rtxCommand:    `no lan1/1 enable`,
			terraformJSON: `{"shutdown":true,"vlan_interface":"lan1/1"}`,
			parseOnly:     false,
			buildOnly:     true,
		},
		{
			name:          "delete_vlan",
			rtxCommand:    `no vlan lan1/1`,
			terraformJSON: `{"vlan_interface":"lan1/1"}`,
			parseOnly:     false,
			buildOnly:     true,
		},
		{
			name:          "delete_vlan_ip",
			rtxCommand:    `no ip lan1/1 address`,
			terraformJSON: `{"vlan_interface":"lan1/1"}`,
			parseOnly:     false,
			buildOnly:     true,
		},
		{
			name:          "delete_vlan_description",
			rtxCommand:    `no description lan1/1`,
			terraformJSON: `{"vlan_interface":"lan1/1"}`,
			parseOnly:     false,
			buildOnly:     true,
		},
		{
			name:          "vlan_id_min",
			rtxCommand:    `vlan lan1/1 802.1q vid=1`,
			terraformJSON: `{"port":"lan1/1","vid":1}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_id_max",
			rtxCommand:    `vlan lan1/1 802.1q vid=4094`,
			terraformJSON: `{"port":"lan1/1","vid":4094}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_port_2",
			rtxCommand:    `vlan lan1/2 802.1q vid=100`,
			terraformJSON: `{"port":"lan1/2","vid":100}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_port_3",
			rtxCommand:    `vlan lan1/3 802.1q vid=200`,
			terraformJSON: `{"port":"lan1/3","vid":200}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_lan2",
			rtxCommand:    `vlan lan2/1 802.1q vid=500`,
			terraformJSON: `{"port":"lan2/1","vid":500}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_ip_address",
			rtxCommand:    `ip vlan1 address 192.168.10.1/24`,
			terraformJSON: `{"address":"192.168.10.1/24","vlan_interface":"vlan1"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
		{
			name:          "vlan_ip_address_2",
			rtxCommand:    `ip vlan2 address 192.168.20.1/24`,
			terraformJSON: `{"address":"192.168.20.1/24","vlan_interface":"vlan2"}`,
			parseOnly:     false,
			buildOnly:     false,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Validate RTX command is not empty
			if strings.TrimSpace(tc.rtxCommand) == "" {
				t.Errorf("RTX command should not be empty")
				return
			}

			// build_only tests (like delete commands) may have empty terraform values
			// because they represent commands that don't have a direct terraform mapping
			if tc.buildOnly {
				t.Logf("Direction: Terraform -> RTX only (build)")
				t.Logf("RTX: %s", tc.rtxCommand)
				t.Logf("Terraform: %s (build_only, may be empty)", tc.terraformJSON)
				return
			}

			// Validate terraform JSON is present and valid for non-build_only tests
			if tc.terraformJSON == "null" || tc.terraformJSON == "" {
				t.Errorf("Terraform value is missing for RTX command: %s", tc.rtxCommand)
				return
			}

			var tfValue interface{}
			if err := json.Unmarshal([]byte(tc.terraformJSON), &tfValue); err != nil {
				t.Errorf("Invalid terraform JSON: %v\nJSON: %s", err, tc.terraformJSON)
				return
			}

			// Log the mapping for visibility
			t.Logf("RTX: %s", tc.rtxCommand)
			t.Logf("Terraform: %s", tc.terraformJSON)

			// Validate that terraform value contains expected fields (only for non-build_only tests)
			if tfMap, ok := tfValue.(map[string]interface{}); ok {
				if len(tfMap) == 0 {
					t.Errorf("Terraform value is empty map for RTX command: %s", tc.rtxCommand)
					return
				}
			}

			// Check mapping direction
			if tc.parseOnly {
				t.Logf("Direction: RTX -> Terraform only (parse)")
			} else {
				t.Logf("Direction: Bidirectional (parse and build)")
			}
		})
	}
}

// TestSpecVlanConfigModelCompatibility tests router model compatibility
func TestSpecVlanConfigModelCompatibility(t *testing.T) {
	// All known RTX router models
	allModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
		"RTX810",
		"NVR700W",
		"NVR510",
		"NVR500",
	}

	// Models that support this command according to the spec
	supportedModels := []string{
		"vRX",
		"RTX5000",
		"RTX3510",
		"RTX3500",
		"RTX1300",
		"RTX1220",
		"RTX1210",
		"RTX840",
		"RTX830",
	}

	// Build a map for quick lookup
	supportedMap := make(map[string]bool)
	for _, m := range supportedModels {
		supportedMap[m] = true
	}

	// Find unsupported models
	var unsupportedModels []string
	for _, m := range allModels {
		if !supportedMap[m] {
			unsupportedModels = append(unsupportedModels, m)
		}
	}

	t.Logf("Command: vlan_config")
	t.Logf("Supported models (%d): %v", len(supportedModels), supportedModels)
	t.Logf("Unsupported models (%d): %v", len(unsupportedModels), unsupportedModels)

	// Test: Verify supported models are recognized
	for _, model := range supportedModels {
		t.Run("supported_"+model, func(t *testing.T) {
			if !IsModelSupported("vlan_config", model) {
				t.Errorf("Model %s should be supported for vlan_config", model)
			}
		})
	}

	// Test: Verify unsupported models are rejected
	for _, model := range unsupportedModels {
		t.Run("unsupported_"+model, func(t *testing.T) {
			if IsModelSupported("vlan_config", model) {
				t.Errorf("Model %s should NOT be supported for vlan_config", model)
			}
		})
	}
}
