package sshd

import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/sh1/terraform-provider-rtx/internal/client"
	"github.com/sh1/terraform-provider-rtx/internal/logging"
	"github.com/sh1/terraform-provider-rtx/internal/provider/fwhelpers"
	"github.com/sh1/terraform-provider-rtx/internal/rtx/parsers"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &SSHDResource{}
	_ resource.ResourceWithImportState = &SSHDResource{}
)

// NewSSHDResource creates a new SSHD resource.
func NewSSHDResource() resource.Resource {
	return &SSHDResource{}
}

// SSHDResource defines the resource implementation.
type SSHDResource struct {
	client client.Client
}

// Metadata returns the resource type name.
func (r *SSHDResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sshd"
}

// Schema defines the schema for the resource.
func (r *SSHDResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages SSH daemon (sshd) configuration on RTX routers. " +
			"This is a singleton resource - only one instance should exist per router. " +
			"WARNING: Disabling SSH while connected via SSH may lock you out of remote management. " +
			"Ensure you have alternative access (console, telnet) before disabling SSH.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Resource identifier (always 'sshd' for this singleton resource).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"enabled": schema.BoolAttribute{
				Description: "Enable or disable the SSH service. WARNING: Disabling SSH may lock you out if connected via SSH.",
				Required:    true,
			},
			"hosts": schema.ListAttribute{
				Description: "List of interfaces to listen on. If empty, listens on all interfaces when enabled.",
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				Validators: []validator.List{
					listvalidator.ValueStringsAre(
						stringvalidator.RegexMatches(
							regexp.MustCompile(`^(lan\d+|pp\d+|bridge\d+|tunnel\d+)$`),
							"must be a valid interface name (e.g., lan1, pp1, bridge1, tunnel1)",
						),
					),
				},
			},
			"host_key": schema.StringAttribute{
				Description: "The SSH host key (read-only, generated by the router). This is sensitive data and should be handled securely.",
				Computed:    true,
				Sensitive:   true,
			},
			"auth_method": schema.StringAttribute{
				Description: "SSH authentication method: password, publickey, or any (default).",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("any"),
				Validators: []validator.String{
					stringvalidator.OneOf("password", "publickey", "any"),
				},
			},
		},
	}
}

// Configure adds the provider configured client to the resource.
func (r *SSHDResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*fwhelpers.ProviderData)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *fwhelpers.ProviderData, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = providerData.Client
}

// Create creates the resource and sets the initial Terraform state.
func (r *SSHDResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data SSHDModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx = logging.WithResource(ctx, "rtx_sshd", "sshd")
	logger := logging.FromContext(ctx)

	config := data.ToClient()
	logger.Debug().Str("resource", "rtx_sshd").Msgf("Creating SSHD configuration: enabled=%v, hosts=%v", config.Enabled, config.Hosts)

	if err := r.client.ConfigureSSHD(ctx, config); err != nil {
		resp.Diagnostics.AddError(
			"Failed to configure SSHD",
			fmt.Sprintf("Could not configure SSHD: %v", err),
		)
		return
	}

	// Set fixed ID for singleton resource
	data.ID = types.StringValue("sshd")

	r.read(ctx, &data, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Read refreshes the Terraform state with the latest data.
func (r *SSHDResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data SSHDModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	r.read(ctx, &data, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Check if resource was removed
	if data.ID.IsNull() {
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// read is a helper function that reads the SSHD configuration from the router.
func (r *SSHDResource) read(ctx context.Context, data *SSHDModel, diagnostics *diag.Diagnostics) {
	ctx = logging.WithResource(ctx, "rtx_sshd", "sshd")
	logger := logging.FromContext(ctx)

	logger.Debug().Str("resource", "rtx_sshd").Msg("Reading SSHD configuration")

	var config *client.SSHDConfig

	// Try to use SFTP cache if enabled
	if r.client.SFTPEnabled() {
		parsedConfig, err := r.client.GetCachedConfig(ctx)
		if err == nil && parsedConfig != nil {
			parsed := parsedConfig.ExtractSSHD()
			if parsed != nil {
				config = convertParsedSSHDConfig(parsed)
				logger.Debug().Str("resource", "rtx_sshd").Msg("Found SSHD config in SFTP cache")
			}
		}
		if config == nil {
			logger.Debug().Str("resource", "rtx_sshd").Msg("SSHD config not in cache, falling back to SSH")
		}
	}

	// Fallback to SSH if SFTP disabled or config not found in cache
	if config == nil {
		var err error
		config, err = r.client.GetSSHD(ctx)
		if err != nil {
			// Check if not configured
			if strings.Contains(err.Error(), "not found") || strings.Contains(err.Error(), "not configured") {
				logger.Debug().Str("resource", "rtx_sshd").Msg("SSHD not configured, removing from state")
				data.ID = types.StringNull()
				return
			}
			fwhelpers.AppendDiagError(diagnostics, "Failed to read SSHD configuration", fmt.Sprintf("Could not read SSHD configuration: %v", err))
			return
		}
	}

	data.FromClient(config)
	data.ID = types.StringValue("sshd")
}

// convertParsedSSHDConfig converts a parser SSHDConfig to a client SSHDConfig
func convertParsedSSHDConfig(parsed *parsers.SSHDConfig) *client.SSHDConfig {
	return &client.SSHDConfig{
		Enabled:    parsed.Enabled,
		Hosts:      parsed.Hosts,
		HostKey:    parsed.HostKey,
		AuthMethod: parsed.AuthMethod,
	}
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *SSHDResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data SSHDModel
	var oldData SSHDModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &oldData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx = logging.WithResource(ctx, "rtx_sshd", "sshd")
	logger := logging.FromContext(ctx)

	config := data.ToClient()
	logger.Debug().Str("resource", "rtx_sshd").Msgf("Updating SSHD configuration: enabled=%v, hosts=%v", config.Enabled, config.Hosts)

	// Warn about potential lockout
	if !oldData.Enabled.IsNull() && oldData.Enabled.ValueBool() && !data.Enabled.ValueBool() {
		logger.Warn().Str("resource", "rtx_sshd").Msg("Disabling SSH service - ensure you have alternative access to the router")
	}

	if err := r.client.UpdateSSHD(ctx, config); err != nil {
		resp.Diagnostics.AddError(
			"Failed to update SSHD configuration",
			fmt.Sprintf("Could not update SSHD configuration: %v", err),
		)
		return
	}

	r.read(ctx, &data, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *SSHDResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data SSHDModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx = logging.WithResource(ctx, "rtx_sshd", "sshd")
	logger := logging.FromContext(ctx)

	logger.Debug().Str("resource", "rtx_sshd").Msg("Deleting SSHD configuration (disabling service)")
	logger.Warn().Str("resource", "rtx_sshd").Msg("Disabling SSH service - ensure you have alternative access to the router")

	if err := r.client.ResetSSHD(ctx); err != nil {
		// Check if it's already gone
		if strings.Contains(err.Error(), "not found") {
			return
		}
		resp.Diagnostics.AddError(
			"Failed to remove SSHD configuration",
			fmt.Sprintf("Could not remove SSHD configuration: %v", err),
		)
		return
	}
}

// ImportState imports an existing resource into Terraform.
func (r *SSHDResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// For singleton resources, accept any import ID and use fixed "sshd" ID
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)

	// Override the ID to always be "sshd"
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), "sshd")...)
}
