package provider

import (
	"context"
	"regexp"
	"strings"

	"github.com/sh1/terraform-provider-rtx/internal/logging"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	"github.com/sh1/terraform-provider-rtx/internal/client"
	"github.com/sh1/terraform-provider-rtx/internal/rtx/parsers"
)

func resourceRTXSSHD() *schema.Resource {
	return &schema.Resource{
		Description: "Manages SSH daemon (sshd) configuration on RTX routers. " +
			"This is a singleton resource - only one instance should exist per router. " +
			"WARNING: Disabling SSH while connected via SSH may lock you out of remote management. " +
			"Ensure you have alternative access (console, telnet) before disabling SSH.",
		CreateContext: resourceRTXSSHDCreate,
		ReadContext:   resourceRTXSSHDRead,
		UpdateContext: resourceRTXSSHDUpdate,
		DeleteContext: resourceRTXSSHDDelete,
		Importer: &schema.ResourceImporter{
			StateContext: resourceRTXSSHDImport,
		},

		Schema: map[string]*schema.Schema{
			"enabled": {
				Type:        schema.TypeBool,
				Required:    true,
				Description: "Enable or disable the SSH service. WARNING: Disabling SSH may lock you out if connected via SSH.",
			},
			"hosts": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "List of interfaces to listen on. If empty, listens on all interfaces when enabled.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
					ValidateFunc: validation.StringMatch(
						regexp.MustCompile(`^(lan\d+|pp\d+|bridge\d+|tunnel\d+)$`),
						"must be a valid interface name (e.g., lan1, pp1, bridge1, tunnel1)",
					),
				},
			},
			"host_key": {
				Type:        schema.TypeString,
				Computed:    true,
				Sensitive:   true,
				Description: "The SSH host key (read-only, generated by the router). This is sensitive data and should be handled securely.",
			},
			"auth_method": {
				Type:         schema.TypeString,
				Optional:     true,
				Default:      "any",
				Description:  "SSH authentication method: password, publickey, or any (default)",
				ValidateFunc: validation.StringInSlice([]string{"password", "publickey", "any"}, false),
			},
		},
	}
}

func resourceRTXSSHDCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	apiClient := meta.(*apiClient)

	// Add resource context for command logging
	ctx = logging.WithResource(ctx, "rtx_sshd", d.Id())
	config := buildSSHDConfigFromResourceData(d)

	logging.FromContext(ctx).Debug().Str("resource", "rtx_sshd").Msgf("Creating SSHD configuration: enabled=%v, hosts=%v", config.Enabled, config.Hosts)

	err := apiClient.client.ConfigureSSHD(ctx, config)
	if err != nil {
		return diag.Errorf("Failed to configure SSHD: %v", err)
	}

	// Use fixed ID for singleton resource
	d.SetId("sshd")

	// Read back to ensure consistency
	return resourceRTXSSHDRead(ctx, d, meta)
}

func resourceRTXSSHDRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	apiClient := meta.(*apiClient)

	// Add resource context for command logging
	ctx = logging.WithResource(ctx, "rtx_sshd", d.Id())
	logger := logging.FromContext(ctx)

	logger.Debug().Str("resource", "rtx_sshd").Msg("Reading SSHD configuration")

	var config *client.SSHDConfig

	// Try to use SFTP cache if enabled
	if apiClient.client.SFTPEnabled() {
		parsedConfig, err := apiClient.client.GetCachedConfig(ctx)
		if err == nil && parsedConfig != nil {
			parsed := parsedConfig.ExtractSSHD()
			if parsed != nil {
				config = convertParsedSSHDConfig(parsed)
				logger.Debug().Str("resource", "rtx_sshd").Msg("Found SSHD config in SFTP cache")
			}
		}
		if config == nil {
			logger.Debug().Str("resource", "rtx_sshd").Msg("SSHD config not in cache, falling back to SSH")
		}
	}

	// Fallback to SSH if SFTP disabled or config not found in cache
	if config == nil {
		var err error
		config, err = apiClient.client.GetSSHD(ctx)
		if err != nil {
			// Check if not configured
			if strings.Contains(err.Error(), "not found") || strings.Contains(err.Error(), "not configured") {
				logger.Debug().Str("resource", "rtx_sshd").Msg("SSHD not configured, removing from state")
				d.SetId("")
				return nil
			}
			return diag.Errorf("Failed to read SSHD configuration: %v", err)
		}
	}

	// Update the state
	if err := d.Set("enabled", config.Enabled); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("hosts", config.Hosts); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("host_key", config.HostKey); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("auth_method", config.AuthMethod); err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// convertParsedSSHDConfig converts a parser SSHDConfig to a client SSHDConfig
func convertParsedSSHDConfig(parsed *parsers.SSHDConfig) *client.SSHDConfig {
	return &client.SSHDConfig{
		Enabled:    parsed.Enabled,
		Hosts:      parsed.Hosts,
		HostKey:    parsed.HostKey,
		AuthMethod: parsed.AuthMethod,
	}
}

func resourceRTXSSHDUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	apiClient := meta.(*apiClient)

	// Add resource context for command logging
	ctx = logging.WithResource(ctx, "rtx_sshd", d.Id())
	config := buildSSHDConfigFromResourceData(d)

	logging.FromContext(ctx).Debug().Str("resource", "rtx_sshd").Msgf("Updating SSHD configuration: enabled=%v, hosts=%v", config.Enabled, config.Hosts)

	// Warn about potential lockout
	if d.HasChange("enabled") {
		oldEnabled, newEnabled := d.GetChange("enabled")
		if oldEnabled.(bool) && !newEnabled.(bool) {
			logging.FromContext(ctx).Warn().Str("resource", "rtx_sshd").Msg("Disabling SSH service - ensure you have alternative access to the router")
		}
	}

	err := apiClient.client.UpdateSSHD(ctx, config)
	if err != nil {
		return diag.Errorf("Failed to update SSHD configuration: %v", err)
	}

	return resourceRTXSSHDRead(ctx, d, meta)
}

func resourceRTXSSHDDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	apiClient := meta.(*apiClient)

	// Add resource context for command logging
	ctx = logging.WithResource(ctx, "rtx_sshd", d.Id())
	logging.FromContext(ctx).Debug().Str("resource", "rtx_sshd").Msg("Deleting SSHD configuration (disabling service)")
	logging.FromContext(ctx).Warn().Str("resource", "rtx_sshd").Msg("Disabling SSH service - ensure you have alternative access to the router")

	err := apiClient.client.ResetSSHD(ctx)
	if err != nil {
		// Check if it's already gone
		if strings.Contains(err.Error(), "not found") {
			return nil
		}
		return diag.Errorf("Failed to remove SSHD configuration: %v", err)
	}

	return nil
}

func resourceRTXSSHDImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	apiClient := meta.(*apiClient)

	logging.FromContext(ctx).Debug().Str("resource", "rtx_sshd").Msg("Importing SSHD configuration")

	// Verify SSHD is configured
	config, err := apiClient.client.GetSSHD(ctx)
	if err != nil {
		return nil, err
	}

	// Set the ID
	d.SetId("sshd")

	// Set attributes
	d.Set("enabled", config.Enabled)
	d.Set("hosts", config.Hosts)
	d.Set("host_key", config.HostKey)
	d.Set("auth_method", config.AuthMethod)

	return []*schema.ResourceData{d}, nil
}

// buildSSHDConfigFromResourceData creates an SSHDConfig from Terraform resource data
func buildSSHDConfigFromResourceData(d *schema.ResourceData) client.SSHDConfig {
	config := client.SSHDConfig{
		Enabled:    d.Get("enabled").(bool),
		Hosts:      []string{},
		AuthMethod: d.Get("auth_method").(string),
	}

	// Parse hosts list
	if v, ok := d.GetOk("hosts"); ok {
		hostsList := v.([]interface{})
		hosts := make([]string, len(hostsList))
		for i, h := range hostsList {
			hosts[i] = h.(string)
		}
		config.Hosts = hosts
	}

	return config
}
